### ISSUE TITLE
AppStudioPlugin.TeamsAppCreateFailed

### ISSUE THREAD

**Issue by nekruza** [OfficeDev/TeamsFx#10143]
**Describe the bug**

[Error] - code:AppStudioPlugin.TeamsAppCreateFailed, message: Failed to create Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 90b7099a-ce0a-4763-bafa-e568d5796c4d. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Error mapping types.\r\n\r\nMapping types:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nType Map configuration:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nDestination Member:\r\nBots\r\n", stack: TeamsAppCreateFailed: Failed to create Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 90b7099a-ce0a-4763-bafa-e568d5796c4d. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Error mapping types.\r\n\r\nMapping types:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nType Map configuration:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nDestination Member:\r\nBots\r\n"
    at Function.SystemError (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7511671)
    at Object.updateTeamsApp (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7451030)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at AppManifest.configure (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7429947)
    at AppManifest.<anonymous> (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:6797529)
    at TeamsfxCore.provision (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:6283469)
    at TeamsfxCore.<anonymous> (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:6797529)
    at FxCore.provisionResourcesOld (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7805526)
    at FxCore.<anonymous> (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7953796)
    at FxCore.exports.ProjectSettingsWriterMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:8030052)
    at FxCore.exports.ContextInjectorMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7942248)
    at FxCore.<anonymous> (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7949249)
    at FxCore.exports.VideoFilterAppBlockerMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:8109778)
    at FxCore.exports.ProjectSettingsLoaderMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:8028499)
    at FxCore.exports.ProjectVersionCheckerMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:8034039)
    at FxCore.exports.AadManifestMigrationMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7921809)
    at FxCore.exports.ProjectConsolidateMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7941960)
    at FxCore.exports.ProjectMigratorMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7990593)
    at FxCore.exports.ConcurrentLockerMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7924472)
    at FxCore.exports.ErrorHandlerMW (/Users/aaa/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-4.2.2/out/src/extension.js:2:7955249)

**Comment by yukun-dong** [comment]
Hello @nekruza,

Could you kindly provide us with your manifest.json file? So that we can check if this error can be reproduced on our side.

Thank you in advance for your assistance.

**Comment by nekruza** [comment]
Hi yukun-dong, thank you for your reply. Please see the manifest.json file below. 

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
    "manifestVersion": "1.11",
    "version": "",
    "id": "b782411c-37d8-440e-ae80-334bd48504f7",
    "packageName": "com.microsoft.teams.extension",
    "developer": {
        "name": "Company Limited",
        "websiteUrl": "https://www.company.io",
        "privacyUrl": "https://www.company.io/privacy",
        "termsOfUseUrl": "https://www.company.io/terms-of-use",
        "mpnId": "6532952"
    },
    "icons": {
        "color": "resources/color.png",
        "outline": "resources/outline.png"
    },
    "name": {
        "short": "Company-debug",
        "full": "Full name for Company-debug"
    },
    "description": {
        "short": "Company.",
        "full": "Company"
    },
    "accentColor": "#FFFFFF",
    "composeExtensions": [],
    "configurableTabs": [
        {
            "configurationUrl": "https://localhost:53000/index.html#/config",
            "canUpdateConfiguration": true,
            "scopes": [
                "team",
                "groupchat"
            ]
        }
    ],
    "staticTabs": [
        {
            "entityId": "index",
            "name": "Dashboard",
            "contentUrl": "https://localhost:53000/index.html#/tab",
            "websiteUrl": "https://localhost:53000/index.html#/tab",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "data",
            "name": "Data",
            "contentUrl": "https://localhost:53000/index.html#/data",
            "websiteUrl": "https://localhost:53000/index.html#/data",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "settings",
            "name": "Settings",
            "contentUrl": "https://localhost:53000/index.html#/settings",
            "websiteUrl": "https://localhost:53000/index.html#/settings",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "conversations",
            "scopes": [
                "personal"
            ]
        }
    ],
    "bots": [
        {
            "botId": "",
            "scopes": [
                "personal"
            ],
            "supportsFiles": false,
            "isNotificationOnly": true
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "Company",
        "localhost",
        "localhost:53000"
    ],
    "webApplicationInfo": {
        "id": "05782a29-0f81-4347-b32d-827428391a76",
        "resource": "api://localhost:53000/05782a29-0f81-4347-b32d-827428391a76"
    },
    "showLoadingIndicator": false
}

**Comment by yukun-dong** [comment]
Hi @nekruza ,
The botId in your manifest is empty which is not valid. If your app doesn't have bot capability, you can just leave the bots section empty, like below:
```json
"bots": [],
```
Please try again and see if it works.

**Comment by nekruza** [comment]
Hi @yukun-dong, the app does have bot capability. However, even if I add a bot id - I still get the same error **([Error] - code:AppStudioPlugin.TeamsAppCreateFailed)**

**Comment by nekruza** [comment]
Hey @yukun-dong, thank you for your message. I have added Bot ID and it worked. However, I am getting another error while uploading a customer app -  "Manifest parsing has failed"

<img width="1276" alt="Screenshot 2023-10-20 at 11 52 25" src="https://github.com/OfficeDev/TeamsFx/assets/90331576/bac887fc-2e8f-4cff-94f7-7ef4bcae96fd">

**Comment by yukun-dong** [comment]
Hi @nekruza ,
This may indicate there is still error in your manifest. You can click "Copy error details to clipboard" to check the details of the error.
