### ISSUE TITLE
TypeError: async_hooks_1.AsyncLocalStorage is not a constructor

### ISSUE THREAD

**Issue by joarobles** [OfficeDev/TeamsFx#1975]
**Describe the bug**
Can't start using the cli with a fresh installation:

**To Reproduce**

```bash
% npm install -g @microsoft/teamsfx-cli
% teamsfx -h

/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2
!function webpackUniversalModuleDefinition(root,factory){if("object"==typeof exports&&"object"==typeof module)module.exports=factory(function webpackLoadOptionalExternalModule(){try{return require("keytar")}catch(e){}}());else if("function"==typeof define&&define.amd)define(["keytar"],factory);else{var a="object"==typeof exports?factory(function webpackLoadOptionalExternalModule(){try{return require("keytar")}catch(e){}}()):factory(root.keytar);for(var i in a)("object"==typeof exports?exports:root)[i]=a[i]}}("undefined"!=typeof self?self:this,(function(__WEBPACK_EXTERNAL_MODULE__36183__){return(()=>{var __webpack_modules__={46136:(__unused_webpack_module,exports)=>{"use strict";var Platform;Object.defineProperty(exports,"__esModule",{value:!0}),exports.Stage=exports.VsCodeEnv=exports.CLIPlatforms=exports.DynamicPlatforms=exports.StaticPlatforms=exports.Platform=exports.ProductName=exports.AppPackageFolderName=exports.ConfigF

TypeError: async_hooks_1.AsyncLocalStorage is not a constructor
    at Object.98228 (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3670971)
    at __webpack_require__ (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:12435116)
    at Object.33754 (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3672794)
    at __webpack_require__ (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:12435116)
    at Object.45049 (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3742227)
    at __webpack_require__ (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:12435116)
    at Object.56437 (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3205765)
    at __webpack_require__ (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:12435116)
    at Object.64213 (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3272100)
    at __webpack_require__ (/Users/qwerty/.npm-global/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:12435116)
```

**Expected behavior**
Help information to be shown.

**CLI Information (please complete the following information):**
 - OS: macOS
 - Version Big Sur 11.5.2
 - node v10.15.3
 - npm 6.10.3

**Comment by MuyangAmigo** [comment]
Hey @joarobles, seems like you are using a older version of node, would it be possible for you to try it on node v14 (LTS version)?

**Comment by joarobles** [comment]
Indeed upgrading Node would solve the issue, thanks!

Where can I see the project requirements?

**Comment by Alive-Fish** [comment]
Hi @joarobles, thanks a lot for your reply! You could find the requirements under this official document (https://aka.ms/teamsfx-cli).
