### ISSUE TITLE
new bug report: AppStudioPlugin.GetRemoteConfigFailed

### ISSUE THREAD

**Issue by ibnekhalid** [OfficeDev/TeamsFx#2317]
Missing configuration data for manifest. Run 'provision' first. Data required: webApplicationInfoResource.

GetRemoteConfigFailed: Missing configuration data for manifest. Run 'provision' first. Data required: webApplicationInfoResource.
    at Function.SystemError (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5168106)
    at AppStudioPluginImpl.getConfigForCreatingManifest (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5155119)
    at AppStudioPluginImpl.getAppDefinitionAndManifest (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5165037)
    at AppStudioPluginImpl.validateManifest (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5138170)
    at AppStudioPlugin.validateManifest (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5125839)
    at AppStudioPlugin.executeUserTask (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5131400)
    at TeamsAppSolution.executeUserTask (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:5743755)
    at TeamsAppSolution.exports.ErrorHandlerMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4689557)
    at FxCore.executeUserTask (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4665614)
    at FxCore.exports.LocalSettingsWriterMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4691800)
    at FxCore.exports.EnvInfoWriterMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4688289)
    at FxCore.exports.ProjectSettingsWriterMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4696159)
    at FxCore.exports.ContextInjecterMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4681702)
    at FxCore.exports.QuestionModelMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4706550)
    at FxCore.<anonymous> (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4707009)
    at FxCore.exports.LocalSettingsLoaderMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4691432)
    at FxCore.<anonymous> (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4687766)
    at FxCore.exports.ProjectSettingsLoaderMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4695044)
    at c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4681179
    at FxCore.exports.ConcurrentLockerMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4681062)
    at FxCore.exports.ErrorHandlerMW (c:\Users\PC-01\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.5.0\out\src\extension.js:2:4689557)

**Comment by yanjiang222** [comment]
Hi @ibnekhalid , thanks for your interested in the toolkit and give your feedback. Just want to double check with if you have resolved the issue? if not, would you mind giving us more context about what you did (steps, things you were doing etc) to help us understand the issue further? Thank you!
