### ISSUE TITLE
Simple Auth not working with personal accounts

### ISSUE THREAD

**Issue by quentin-pla** [OfficeDev/TeamsFx#2967]
**Describe the bug**
When trying to use TeamsFx Simple Auth in back-end with TeamsFx SDK in front-end with a personal account, I have a critical error when registering the token to the endpoint /auth/token.

**To Reproduce**
1. Connect to Teams with personal account
2. Initialize TeamsFx SDK in front-end
2. Create TeamsUserCredential
3. Call login or getToken functions from credential with some scopes
4. After token is retrieved, it cannot be registered to /auth/token endpoint

**Expected behavior**
After token is retrieved, it should be registered and user should be able to use application.

**Console Error**
`crit: TeamsPro.Shared.Api.Http.HttpResponseExceptionFilter[0]
      Critical error encountered
Microsoft.TeamsFx.SimpleAuth.Components.Auth.Exceptions.AadUiRequiredException: AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: 40b37bb2-30f0-41e6-96a1-07ad3813d600
Correlation ID: ff029d79-c264-40de-9831-b93ecf1e1498
Timestamp: 2021-11-15 15:15:31Z
 ---> MSAL.NetCore.4.30.0.0.MsalUiRequiredException:
        ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: 40b37bb2-30f0-41e6-96a1-07ad3813d600
Correlation ID: ff029d79-c264-40de-9831-b93ecf1e1498
Timestamp: 2021-11-15 15:15:31Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshError(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.OnBehalfOfRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenOnBehalfOfParameters onBehalfOfParameters, CancellationToken cancellationToken)
   at Microsoft.TeamsFx.SimpleAuth.Components.Auth.AuthHandler.AcquireTokenBySsoTokenOnBehalfOf(String ssoToken, String[] scopes)
        StatusCode: 400
        ResponseBody: {"error":"invalid_grant","error_description":"AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.\r\nTrace ID: 40b37bb2-30f0-41e6-96a1-07ad3813d600\r\nCorrelation ID: ff029d79-c264-40de-9831-b93ecf1e1498\r\nTimestamp: 2021-11-15 15:15:31Z","error_codes":[500202],"timestamp":"2021-11-15 15:15:31Z","trace_id":"40b37bb2-30f0-41e6-96a1-07ad3813d600","correlation_id":"ff029d79-c264-40de-9831-b93ecf1e1498"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: ff029d79-c264-40de-9831-b93ecf1e1498
x-ms-request-id: 40b37bb2-30f0-41e6-96a1-07ad3813d600
x-ms-ests-server: 2.1.12231.7 - WEULR1 ProdSlices
x-ms-clitelem: 1,500202,0,,
Set-Cookie: fpc=AhExlkC6chhFnCGx1O7_rNE4YUc6AQAAAJNwJNkOAAAA; expires=Wed, 15-Dec-2021 15:15:31 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Mon, 15 Nov 2021 15:15:31 GMT
   --- End of inner exception stack trace ---
   at Microsoft.TeamsFx.SimpleAuth.Components.Auth.AuthHandler.AcquireTokenBySsoTokenOnBehalfOf(String ssoToken, String[] scopes)
   at Microsoft.TeamsFx.SimpleAuth.Controllers.AuthController.AcquireAccessTokenBySsoToken(PostTokenRequestBody body)
   at Microsoft.TeamsFx.SimpleAuth.Controllers.AuthController.PostToken(PostTokenRequestBody body)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

**Simple Auth Extension Information:**
 - OS: macOS Monterey
 - Version 0.1.0

**SDK Information:**
 - OS: macOS Monterey
 - Version 0.3.2

**Comment by blackchoey** [comment]
Hi @quentin-pla thanks for reaching us. Unfortunately, personal account is not supported by the tooling temporary. We will review your feature request and reach you back once we have any update.
The workaround is not simple because many components in your app need to be adjusted. We will also reach you back when there's a suitable workaround that is easy for you to operate.
