### ISSUE TITLE
Obtain Client Secret From Key Vault

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#3330]
**Describe the bug**
I would like to be able to obtain the client secret and a few other things from Azure Key Vault. In .Net 5.0 I would set that up in program.cs. When I create a new app based off the toolkit,  the client secret is written into the secrets.json file and named CLIENT_SECRET. This naming violates the rules for secret naming in the key vault. I have been unable to find any other reference to the client secret in code, but it appears to be used somewhere as its absense or being renamed to ClientSecret will throw an error about missing secret.

**To Reproduce**
1. Create new Teams Tab app
2. Go to user secrets file
3. Rename CLIENT_SECRET to ClientSecret
4. Run the app
5. See error below

Failed to get access token from authentication server: Value cannot be null. (Parameter 'clientSecret') ErrorWithCode.ServiceError: Failed to get access token from authentication server: Value cannot be null. (Parameter 'clientSecret') at He.generateAuthServerError (https://localhost:44357/_content/Microsoft.TeamsFx/teamsfx.js:15:81966) at He.<anonymous> (https://localhost:44357/_content/Microsoft.TeamsFx/teamsfx.js:15:79221) at Generator.throw (<anonymous>) at s (https://localhost:44357/_content/Microsoft.TeamsFx/teamsfx.js:15:216)

**Expected behavior**
This is what I expected. The name of the client secret appears to be hard coded into teamsfx.js. I would like to name it according to Azure Key Vault rules so I can use key vault in a production setting

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 21H2 22000.348
 - Microsoft Visual Studio Professional 2019 Version 16.11.7
 - Teams Toolkit 0.1.107.31731

**Additional context**
I would like to be able to minimize the data in appsettings.json to only the values required to grab everything else from key vault. This will keep secret values out of GIT and configuration files in production.

Thanks

**Comment by JerryYangKai** [comment]
@grumpykiwi  This CLIENT_SECRET naming is hard code in SimpleAuth nuget package, you could find it in dependency.
Also you could find the entrance in startup.cs 
`services.AddTeamsFxSimpleAuth(Configuration);`
It input is the configuration.

**Comment by JerryYangKai** [comment]
Add @blackchoey for more info. 
Do we have some solutions to help our user to fix it?

**Comment by blackchoey** [comment]
Hi @grumpykiwi Since Key Vault has limitations on the secret name, the key vault provider provides a way to let you map the secret name to configuration name: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azurekeyvault.ikeyvaultsecretmanager?view=dotnet-plat-ext-3.1
Can you try this way to map secret name to correct configuration name?

**Comment by grumpykiwi** [comment]
Thanks I’ll take a look at th

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________

**Comment by grumpykiwi** [comment]
Thanks Jerry. Will take a look at this first thing in the morning

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________

**Comment by grumpykiwi** [comment]
Hi

I followed the instructions (I think) but can't get it to compile. I created a standalone blazor app to test with to avoid going thru the chore of testing within teams

Program.cs

using Azure.Identity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Azure.KeyVault;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using System;
using System.Linq;
using System.Security.Cryptography.X509Certificates;

namespace BlazorKeyVaultTest
{
     public class Program
     {
           public static void Main( string[] args )
           {
                CreateHostBuilder(args).Build().Run();
           }

           public static IHostBuilder CreateHostBuilder( string[] args ) =>
                Host.CreateDefaultBuilder(args)
                     .ConfigureAppConfiguration(( context, config ) =>
                     {
                           var builtConfig = config.Build();
                           var certThumbprint = builtConfig.GetValue<string>("CertThumbprint");
                           var store = new X509Store(StoreLocation.LocalMachine);
                           store.Open(OpenFlags.ReadOnly);
                           var certs = store.Certificates.Find(X509FindType.FindByThumbprint, certThumbprint, false);
                           var tenantId = builtConfig.GetValue<string>("TenantId");
                           var clientId = builtConfig.GetValue<string>("ClientId");
                           var vaultName = builtConfig.GetValue<string>("KeyVaultName");
                           config.AddAzureKeyVault(
                                new Uri($"https://{vaultName}.vault.azure.net/"),
                                new ClientCertificateCredential(tenantId, clientId, certs.OfType<X509Certificate2>().Single()),
                                new PrefixKeyVaultSecretManager(builtConfig["WEBAPP_NAME"]));

                           store.Close();

                     })
                     .ConfigureWebHostDefaults(webBuilder =>
                     {
                           webBuilder.UseStartup<Startup>();
                     });
     }
}

PrefixKeyVaultSecretManager.cs

using Microsoft.Azure.KeyVault.Models;
using Microsoft.Extensions.Configuration.AzureKeyVault;

public class PrefixKeyVaultSecretManager : IKeyVaultSecretManager
{
     private readonly string _prefix;

     public PrefixKeyVaultSecretManager( string prefix )
     {
           _prefix = $"{prefix}-";
     }

     public bool Load( SecretItem secret )
     {
           //              var mySecret = secret;
           return true;
     }

     public string GetKey( SecretBundle secret )
     {
           return secret.SecretIdentifier.Name.Replace("-", "");
           //              return $"KeyVaultObjects:{secret.SecretIdentifier.Name}";
     }
}

Index.razor

@page "/"
@using Microsoft.Extensions.Configuration
@using System.Linq
@inject IConfiguration Configuration

***@***.***</h6>

@code
{
     public string str = "";
     const string SectionDelimiter = "_";

     protected override void OnInitialized()
     {
           base.OnInitialized();

           IConfigurationRoot root = (IConfigurationRoot) Configuration;
           foreach (var provider in root.Providers.ToList())
           {
                if (provider.ToString().Contains("AzureKeyVaultConfigurationProvider"))
                {
                     var keyValues = provider.GetChildKeys(Enumerable.Empty<string>(), null);
                     foreach(var key in keyValues)
                     {
                           provider.TryGet(key, out var value);

                           str += $"Key: {key} - Value: {value}\r\n";
                     }
                }
           }
     }
}

In the Azure Key Vault I defined a secret named Client-Secret

The text in green above causes a compiler error.

Error      CS1503  Argument 4: cannot convert from 'PrefixKeyVaultSecretManager' to 'Azure.Extensions.AspNetCore.Configuration.Secrets.KeyVaultSecretManager'

I am probably missing something obvious, but after fiddling with it for several hours, I am at a loss.

The PrefixKeyVaultSecretManager should return a config keyname of ClientSecret, which is what the Blazor app is expecting. ClientSecret was removed from the appsettings.json for this test scenario.

If I change IKeyVaultSecretManager to KeyVaultSecretManager in the PrefixKeyVaultSecretManager class, it will compile, but the class never seems to get called. I print out the values on my index.razor page and the key name from Key Vault is unchanged.

Ideas?




Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by blackchoey** [comment]
@grumpykiwi I noticed you're using another nuget package, so it's correct to change `IKeyVaultSecretManager` to `KeyVaultSecretManager`. You can find`KeyVaultSecretManager` is documented in `Azure.Extensions.AspNetCore.Configuration.Secrets`'s [API](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.Configuration.Secrets_1.2.1/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/api/Azure.Extensions.AspNetCore.Configuration.Secrets.netstandard2.0.cs#L16).

For the problem that your `PrefixKeyVaultSecretManager` seems not being called, we need to have a try in our side and reach back to you later. In the meantime, can you also raise an issue at https://github.com/Azure/azure-sdk-for-net for your secret manager not being called problem? So we can work parallelly to solve your problem.

**Comment by grumpykiwi** [comment]
If there is a different package I should try, let me know in order to try getting ikeyvaultsecretmanager to compile in the meantime.

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________

**Comment by blackchoey** [comment]
@grumpykiwi Please keep using `Azure.Extensions.AspNetCore.Configuration.Secrets` package and implementing `KeyVaultSecretManager` class as what you're doing now. I dig a little more and found the package that contains `IKeyVaultSecretManager` has been deprecated. I will work internally to make sure the document is up-to-date.
Let's try to get your customized `KeyVaultSecretManager` work.

**Comment by grumpykiwi** [comment]
Ahh. Sounds good. Explains things. Will work on it tomorrow thanks

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________

**Comment by grumpykiwi** [comment]
I believe I fixed it.

Project file.csproj

`  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" />
    <PackageReference Include="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.22" />
  </ItemGroup>`

program.cs
```
			.ConfigureAppConfiguration((context, config) =>
				{
					var builtConfig = config.Build();
					var certThumbprint = builtConfig.GetValue<string>("CertThumbprint");
					var store = new X509Store(StoreLocation.LocalMachine);
					store.Open(OpenFlags.ReadOnly);
					var certs = store.Certificates.Find(X509FindType.FindByThumbprint, certThumbprint, false);
					var tenantId = builtConfig.GetValue<string>("TenantId");
					var clientId = builtConfig.GetValue<string>("ClientId");
					var vaultName = builtConfig.GetValue<string>("KeyVaultName");
					var appName = builtConfig.GetValue<string>("WebAppName");
					var clientCertificateCredential = new ClientCertificateCredential(tenantId, clientId, certs.OfType<X509Certificate2>().Single());

					var secretClient = new SecretClient(new Uri($"https://{vaultName}.vault.azure.net/"), clientCertificateCredential);

					config.AddAzureKeyVault(secretClient, 
						new PrefixKeyVaultSecretManager(appName));

					store.Close();

				})
```
PrefixKeyVaultSecretManager.cs

```
using Azure.Extensions.AspNetCore.Configuration.Secrets;
using Azure.Security.KeyVault.Secrets;

public class PrefixKeyVaultSecretManager : KeyVaultSecretManager
{
	private readonly string _prefix;

	public PrefixKeyVaultSecretManager (string prefix)
	{
		_prefix = $"{prefix}-";
	}

	public override bool Load (SecretProperties secret)
	{
		return true;
	}

	public override string GetKey (KeyVaultSecret secret)
	{
		return secret.Name.Replace("-", "_");
	}
}
```
The key is a combo of the right packages and making sure the methods in PrefixKeyVaultSecretManager have the override keyword to make sure they actually get called. After that you can do all the string matching and replacing you need inside the GetKey() method. This will affect app start time apparently, but I haven't noticed any measurable differences.

**Comment by blackchoey** [comment]
Cool~ Congratulations @grumpykiwi ! Do you have any other questions regarding this issue?

**Comment by grumpykiwi** [comment]
As long as it is documented and/or the extension modified, I am happy.

Thanks for pointing me in the right direction.

**Comment by blackchoey** [comment]
Thanks. We already have plan to improve the coding experience, so you don't need to use a customized key vault secret manager to map your secret to another name.
