### ISSUE TITLE
Javascript Message Extension App fails to pass npm install step

### ISSUE THREAD

**Issue by jk-msft** [OfficeDev/TeamsFx#5429]
**Describe the bug**
When you attempt to run Javascript Message Extension App using local debug mode, the start up process fails when you attempt to run `npm install`

**To Reproduce**
1. Go to Teams Toolkit on VSCode
2. Click on Create a new Teams app
3. Click "create a new Teams app"
4. Choose Message extension.
5. Choose Javascript
6. Select some folder
7. Give it a name
8. Click "Local Debug" bottom right.
9. Choose Debug Chrome or Debug Edge
10. Note the failure
```
× NPM Install for bot app
   Failed to npm install for bot
```
![Screen Shot 2022-06-30 at 3 43 38 PM](https://user-images.githubusercontent.com/107141247/176790710-0e8c03e0-22b3-499d-bd83-09ce1f89eae8.png)

When I look at the error log, this is what I see

```
1486 timing command:install Completed in 20247ms
1487 verbose type range
1488 verbose stack adaptivecards-templating: No matching version found for adaptivecards-templating@^2.1.0.
1488 verbose stack     at module.exports (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
1488 verbose stack     at RegistryFetcher.manifest (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:24)
1488 verbose stack     at async Promise.all (index 3)
1488 verbose stack     at async Arborist.[buildDepStep] (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1093:5)
1488 verbose stack     at async Arborist.buildIdealTree (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
1488 verbose stack     at async Promise.all (index 1)
1488 verbose stack     at async Arborist.reify (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
1488 verbose stack     at async Install.exec (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/lib/commands/install.js:156:5)
1488 verbose stack     at async module.exports (/Users/kimjason/.nvm/versions/node/v16.15.1/lib/node_modules/npm/lib/cli.js:78:5)
1489 verbose cwd /Users/kimjason/projects/teams-tutorials/npminstallPass/bot
1490 verbose Darwin 21.5.0
1491 verbose node v16.15.1
1492 verbose npm  v8.11.0
1493 error code ETARGET
1494 error notarget No matching version found for adaptivecards-templating@^2.1.0.
1495 error notarget In most cases you or one of your dependencies are requesting
1495 error notarget a package version that doesn't exist.
1496 verbose exit 1
1497 timing npm Completed in 20467ms
1498 verbose unfinished npm timer reify 1656628971466
1499 verbose unfinished npm timer reify:loadTrees 1656628971487
1500 verbose code 1
1501 error A complete log of this run can be found in:
1501 error     /Users/kimjason/.npm/_logs/2022-06-30T22_42_51_248Z-debug-0.log
```

**Expected behavior**
I should be able to pass the npm install step.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS:  OSX

**CLI Information (please complete the following information):**

**Additional context**

**Comment by JerryYangKai** [comment]
Hi @jk-msft, thanks for posting this issue, I am trying to repro your bug but I could not repro it in a clean OSX with node 16.15.1.
What I suggest is could you please upgrade the VS code and Teams Toolkit to the latest version and try again?
If the bug still exist, the second solution is clean your npm global package and clean it.
Hope it will help you.
