### ISSUE TITLE
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Unable to convert "meetingStage" to Enum "xxxx.Interop.TeamsSDK.FrameContext

### ISSUE THREAD

**Issue by MRoutchkan** [OfficeDev/TeamsFx#5483]
**Describe the bug**
getting the context in the tab that was placed on stage after click "start presenting .." button throws an Error

`var context = await MicrosoftTeams.GetTeamsContextAsync();`

[2022-07-08T10:53:59.528Z] Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Unable to convert "meetingStage" to Enum "rmTeamsPresenter.Interop.TeamsSDK.FrameContext".. See InnerException for more details.
 ---> System.Text.Json.JsonException: Unable to convert "meetingStage" to Enum "rmTeamsPresenter5.Interop.TeamsSDK.FrameContext".
   at rmTeamsPresenter5.Interop.TeamsSDK.EnumDescriptionConverter'1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\Users\m.routchkan\source\repos\rmTeamsPresenter5\rmTeamsPresenter5\Interop\TeamsSDK\EnumDescriptionConverter.cs:line 21
   at System.Text.Json.Serialization.JsonConverter'1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo'1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter'1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter'1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter'1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at rmTeamsPresenter5.Interop.InteropModuleBase.InvokeAsync[T](String functionName, Object[] args) in C:\Users\m.routchkan\source\repos\rmTeamsPresenter5\rmTeamsPresenter5\Interop\InteropModuleBase.cs:line 0
   at rmTeamsPresenter5.Pages.Tab.OnAfterRenderAsync(Boolean firstRender) in C:\Users\m.routchkan\source\repos\rmTeamsPresenter5\rmTeamsPresenter5\Pages\Tab.razor:line 54
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**To Reproduce**
Steps to reproduce the behavior in the Teams App
1. place `var context = await MicrosoftTeams.GetTeamsContextAsync();`
in the function `OnAfterRenderAsync(bool firstRender)` on Tab.razor
2. add your app to the meeting in the Teams App and open it in the sidebar
3. Click on 'start presenting ...'
4. See an error "An error has occurred. This application may no longer respond until reloaded. [Reload]"

Steps to reproduce the behavior in the Teams WebApp
1. place `var context = await MicrosoftTeams.GetTeamsContextAsync();`
in the function `OnAfterRenderAsync(bool firstRender)` on Tab.razor
2. switch your Teams WebApp to Developer Preview
3. add your app to the meeting in the Teams WebApp and open it in the sidebar
3. Click on 'start presenting ...'
4. See error "An error has occurred. This application may no longer respond until reloaded. [Reload]"
5. See the detailed error in the console (`builder.Services.AddServerSideBlazor().AddCircuitOptions(options => { options.DetailedErrors = true; });` is reqiered)

**Expected behavior**
the app content should be shown on the meeting stage

**Screenshots**
![Screenshot 2022-07-08 133710](https://user-images.githubusercontent.com/3243311/177985248-72bbfb7c-17c2-4a86-9168-a2a97c26b418.png)
![Screenshot 2022-07-08 133821](https://user-images.githubusercontent.com/3243311/177985251-ba14444d-48db-45ef-882a-eb43fe7febb5.png)

**VS 2022 + Teams Toolkit + Blazor**
 - OS: Windows 10
 - Version 17.2.5
 - teamsFx 1.0.0

**Comment by JerryYangKai** [comment]
@MRoutchkan Thanks reporting this issue, I will start to repro the bug and find the reason.

**Comment by JerryYangKai** [comment]
@MRoutchkan  Hi, this error caused from the Interop part in our template code.
Because of Teams SDK do not have the C# version, so we wrapper it as a simple one. 
You could check the line 230 in TeamsContext.cs, we have not add the meetingStage in the Enum class, since it can be edit by developer, I suggest you could add this in the enum and try again.
Thanks!

**Comment by MRoutchkan** [comment]
Hello @JerryYangKai, thank you! it works!
