### ISSUE TITLE
AppStudioPlugin.LocalAppIdUpdateFailed

### ISSUE THREAD

**Issue by joshua-d-brown** [OfficeDev/TeamsFx#5649]
One of our team members is unable to run our Teams app locally. He gets this error message:

[Error] - code:AppStudioPlugin.LocalAppIdUpdateFailed, message: Failed to update local debug Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Could not find a part of the path 'F:\\SvcFab\\_App\\AppStudioType_App0\\temp\\ASPNETCORE_eb6ae43e-73b6-450a-918a-c3bfdb36687d.tmp'.", stack: LocalAppIdUpdateFailed: Failed to update local debug Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Could not find a part of the path 'F:\\SvcFab\\_App\\AppStudioType_App0\\temp\\ASPNETCORE_eb6ae43e-73b6-450a-918a-c3bfdb36687d.tmp'."
	at Function.SystemError (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6199930)
	at AppStudioPluginImpl.updateApp (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6192205)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async AppStudioPluginImpl.postLocalDebug (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6182508)
	at async AppStudioPlugin.postLocalDebug (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6144034)
	at async Object.configureLocalResourceAdapter (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6849988)
	at async AppStudioPluginV2.configureLocalResource (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6209305)
	at async Promise.all (index 3)
	at async Object.executeConcurrently (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:7173447)
	at async TeamsAppSolutionV2.provisionLocalResource (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:7236041)
	at async FxCore.localDebugV2 (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5338792)
	at async FxCore.<anonymous> (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5473600)
	at async FxCore.exports.ProjectSettingsWriterMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5525594)
	at async FxCore.exports.ContextInjectorMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5461359)
	at async FxCore.exports.QuestionModelMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5536423)
	at async FxCore.SolutionLoaderMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5543887)
	at async FxCore.<anonymous> (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5468709)
	at async FxCore.exports.ProjectSettingsLoaderMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5524117)
	at async FxCore.exports.ProjectVersionCheckerMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5528747)
	at async FxCore.exports.AadManifestMigrationMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5441161)
	at async FxCore.exports.ProjectConsolidateMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5461071)
	at async FxCore.exports.ProjectMigratorMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5520517)
	at async FxCore.exports.ConcurrentLockerMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5443620)
	at async FxCore.exports.ErrorHandlerMW (c:\Users\leohi\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5477139)

**Comment by nliu-ms** [comment]
Thanks @joshua-d-brown , it seems to be an intermittent error from Teams Developer Portal, but from telemetry it should work now. Can you please try it again and tell me your current status? Thanks!

**Comment by nliu-ms** [comment]
Hey @joshua-d-brown , just wondering if you still meet this error?

**Comment by joshua-d-brown** [comment]
No, but the only solution we found was to downgrade the Teams Toolkit Extension from 4.0.3 to 4.0.0. Then everything worked fine.

**Comment by nliu-ms** [comment]
@joshua-d-brown  It is actually an intermittent server error. So the version of Teams Toolkit should not be the root cause. I guess when you downgrade to 4.0.0 the server is recovered, which seems like that downgrading works. Can you please try 4.0.3 again? Thanks!

**Comment by dasibre** [comment]
So, I'm running version 4.0.4, and I keep running into the same error locally. Not sure if its intermittent server error, but constantly fails, and only works when I downgrade to version 4.0.0
1
