### ISSUE TITLE
[Error] - code:AppStudioPlugin.LocalAppIdUpdateFailed, message: Failed to update local debug Teams app in Developer Portal

### ISSUE THREAD

**Issue by contactkanika12** [OfficeDev/TeamsFx#5723]
[Error] - code:AppStudioPlugin.LocalAppIdUpdateFailed, message: Failed to update local debug Teams app in Developer Portal, due to Missing configuration data for manifest. You may need to run 'Local debug' first. Data required: state.fx-resource-frontend-hosting.endpoint, stack: LocalAppIdUpdateFailed: Failed to update local debug Teams app in Developer Portal, due to Missing configuration data for manifest. You may need to run 'Local debug' first. Data required: state.fx-resource-frontend-hosting.endpoint
	at Function.SystemError (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6199930)
	at AppStudioPluginImpl.updateApp (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6192205)
	at async AppStudioPluginImpl.postLocalDebug (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6182508)
	at async AppStudioPlugin.postLocalDebug (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6144034)
	at async Object.configureLocalResourceAdapter (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6849988)
	at async AppStudioPluginV2.configureLocalResource (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:6209305)
	at async Promise.all (index 3)
	at async Object.executeConcurrently (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:7173447)
	at async TeamsAppSolutionV2.provisionLocalResource (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:7236041)
	at async FxCore.localDebugV2 (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5338792)
	at async FxCore.<anonymous> (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5473600)
	at async FxCore.exports.ProjectSettingsWriterMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5525594)
	at async FxCore.exports.ContextInjectorMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5461359)
	at async FxCore.exports.QuestionModelMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5536423)
	at async FxCore.SolutionLoaderMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5543887)
	at async FxCore.<anonymous> (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5468709)
	at async FxCore.exports.ProjectSettingsLoaderMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5524117)
	at async FxCore.exports.ProjectVersionCheckerMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5528747)
	at async FxCore.exports.AadManifestMigrationMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5441161)
	at async FxCore.exports.ProjectConsolidateMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5461071)
	at async FxCore.exports.ProjectMigratorMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5520517)
	at async FxCore.exports.ConcurrentLockerMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5443620)
	at async FxCore.exports.ErrorHandlerMW (c:\Users\kagupta\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.0.3\out\src\extension.js:2:5477139)

**Comment by nliu-ms** [comment]
Thanks @contactkanika12  for reporting this bug. Have you manually updated the state.local.json file or manifest.template.json file? As this error indicating that `state.fx-resource-frontend-hosting.endpoint` cannot be found and replaced in manifest template.
