### ISSUE TITLE
JSON error: Expected the input to start with a valid JSON token, when isFinalBlock is true.

### ISSUE THREAD

**Issue by grandyang** [OfficeDev/TeamsFx#6436]
Hi

I am following [this tpost](https://devblogs.microsoft.com/microsoft365dev/post-notifications-to-microsoft-teams-with-net-using-teams-toolkit-for-visual-studio/) to develop a notification bot, the difference is that I choose the `HTTP Trigger (Web API Server)` as the trigger type. But when i run the app without any additional change, I got the following error, can any one help me fix it?

```
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)

   at System.Text.Json.Utf8JsonReader.Read()

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   --- End of inner exception stack trace ---

   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)

   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)

   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)

   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)

   at Microsoft.TeamsFx.Conversation.LocalFileStorage.ReadFromFile(CancellationToken cancellationToken)

   at Microsoft.TeamsFx.Conversation.LocalFileStorage.List(CancellationToken cancellationToken)

   at Microsoft.TeamsFx.Conversation.NotificationBot.GetInstallationsAsync(CancellationToken cancellationToken)

   at NotificationBot.Controllers.NotificationController.PostAsync(CancellationToken cancellationToken) in C:\Users\xiaochenyang\Source\Repos\NotificationBot\Controllers\NotificationController.cs:line 27

   at lambda_method4(Closure , Object )

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by xiaolang124** [comment]
Do you mean you can start and install your app in Teams, but fail to trigger http notification? May I ask how do you trigger the notification?

You can try these two methods to trigger the notication.
- Open Powershell and post an HTTP request to trigger the notification:
   Invoke-WebRequest -Uri "http://localhost:5130/api/notification" -Method Post
- Open Postman and send post request to "http://localhost:5130/api/notification"

 
![image](https://user-images.githubusercontent.com/13211513/197474897-6d649740-e218-49c9-8910-272d015a0048.png)

**Comment by wh-alice** [comment]
Close stale issues. Please create new issue then we can support.
