### ISSUE TITLE
bug report: AppStudioPlugin.LocalAppIdUpdateFailed

### ISSUE THREAD

**Issue by VVMig** [OfficeDev/TeamsFx#6692]
[AppStudioPlugin.LocalAppIdUpdateFailed]: Failed to update local debug teams app in app studio, due to 503, Cannot create teams app due to Error: Request failed with status code 503

[Error] - code:AppStudioPlugin.LocalAppIdUpdateFailed, message: Failed to update local debug teams app in app studio, due to 503, Cannot create teams app due to Error: Request failed with status code 503, stack: LocalAppIdUpdateFailed: Failed to update local debug teams app in app studio, due to 503, Cannot create teams app due to Error: Request failed with status code 503
	at Function.SystemError (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5958611)
	at AppStudioPluginImpl.updateApp (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5948582)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async AppStudioPluginImpl.getAppDefinitionAndUpdate (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5910169)
	at async AppStudioPluginImpl.postLocalDebug (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5932645)
	at async AppStudioPlugin.postLocalDebug (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5885644)
	at async Object.configureLocalResourceAdapter (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:6617114)
	at async AppStudioPluginV2.configureLocalResource (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5970158)
	at async Promise.all (index 3)
	at async Object.executeConcurrently (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:6923098)
	at async TeamsAppSolutionV2.provisionLocalResource (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:6972522)
	at async FxCore.localDebugV2 (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5137346)
	at async FxCore.exports.LocalSettingsWriterMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5257881)
	at async FxCore.<anonymous> (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5250167)
	at async FxCore.exports.ProjectSettingsWriterMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5304764)
	at async FxCore.exports.ContextInjectorMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5238494)
	at async FxCore.exports.QuestionModelMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5310976)
	at async FxCore.SolutionLoaderMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5320880)
	at async FxCore.exports.LocalSettingsLoaderMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5257418)
	at async FxCore.<anonymous> (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5245502)
	at async FxCore.exports.ProjectSettingsLoaderMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5303324)
	at async FxCore.exports.ProjectConsolidateMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5238268)
	at async FxCore.exports.ProjectMigratorMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5300151)
	at async FxCore.exports.ConcurrentLockerMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5227205)
	at async FxCore.exports.ErrorHandlerMW (/Users/vladimir.migay/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-3.7.0/out/src/extension.js:2:5253291)

**Comment by adashen** [comment]
close as duplicate with https://github.com/OfficeDev/TeamsFx/issues/6723
