### ISSUE TITLE
Bug report:  I've got the error below  after creating and deploying a sample for message extension with Teams Toolkit  

### ISSUE THREAD

**Issue by tuxxon** [OfficeDev/TeamsFx#7161]
**Describe the bug**
 I've got the error below  after creating and deploying a sample for message extension with Teams Toolkit.
```
response: {
    headers: HttpHeaders { _headersMap: [Object] },
    request: WebResource {
      streamResponseBody: undefined,
      url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585311211128856785?api-version=2021-01-01',
      method: 'GET',
      headers: [HttpHeaders],
      body: undefined,
      query: undefined,
      formData: undefined,
      withCredentials: false,
      abortSignal: undefined,
      timeout: 0,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      proxySettings: undefined,
      keepAlive: undefined,
      agentSettings: undefined,
      redirectLimit: undefined,
      operationSpec: [Object],
      operationResponseGetter: [Function: getOperationResponse]
    },
    status: 200,
    readableStreamBody: undefined,
    bodyAsText: `{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\\r\\n  \\"status\\": \\"Failed\\",\\r\\n  \\"error\\": {\\r\\n    \\"code\\": \\"ResourceDeploymentFailure\\",\\r\\n    \\"message\\": \\"The resource operation completed with terminal provisioning state 'Failed'.\\",\\r\\n    \\"details\\": [\\r\\n      {\\r\\n        \\"code\\": \\"DeploymentFailed\\",\\r\\n        \\"message\\": \\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\",\\r\\n        \\"details\\": [\\r\\n          {\\r\\n            \\"code\\": \\"Conflict\\",\\r\\n            \\"message\\": \\"{\\\\r\\\\n  \\\\\\"status\\\\\\": \\\\\\"Failed\\\\\\",\\\\r\\\\n  \\\\\\"error\\\\\\": {\\\\r\\\\n    \\\\\\"code\\\\\\": \\\\\\"ResourceDeploymentFailure\\\\\\",\\\\r\\\\n    \\\\\\"message\\\\\\": \\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\",\\\\r\\\\n    \\\\\\"details\\\\\\": [\\\\r\\\\n      {\\\\r\\\\n        \\\\\\"code\\\\\\": \\\\\\"DeploymentFailed\\\\\\",\\\\r\\\\n        \\\\\\"message\\\\\\": \\\\\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\\\\",\\\\r\\\\n        \\\\\\"details\\\\\\": [\\\\r\\\\n          {\\\\r\\\\n            \\\\\\"code\\\\\\": \\\\\\"BadRequest\\\\\\",\\\\r\\\\n            \\\\\\"message\\\\\\": \\\\\\"{\\\\\\\\r\\\\\\\\n  \\\\\\\\\\\\\\"error\\\\\\\\\\\\\\": {\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"code\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"InvalidBotData\\\\\\\\\\\\\\",\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"message\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"Bot is not valid. Errors: Microsoft App ID is required.  See https://docs.microsoft.com/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0 for detailed requirements.\\\\\\\\\\\\\\"\\\\\\\\r\\\\\\\\n  }\\\\\\\\r\\\\\\\\n}\\\\\\"\\\\r\\\\n          }\\\\r\\\\n        ]\\\\r\\\\n      }\\\\r\\\\n    ]\\\\r\\\\n  }\\\\r\\\\n}\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}"}]}}`,
    redirected: false,
    url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585311211128856785?api-version=2021-01-01',
    parsedBody: { status: 'Failed', error: [Object] }
  },
  body: {
    status: 'Failed',
    error: {
      code: 'DeploymentFailed',
      message: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.',
      details: [Array]
    }
  }
```

**To Reproduce**
1.  Install Visual Source Code and Teams Toolkit.
2. Click on 'Teams Toolkit' and Select Development.
3. Select 'Create a new teams app'.
4. Select 'Message extension' and Save it to your folder. in my case I've created a folder on ubuntu in WSL.
5. run the following commands:
   $ teamsfx account login azure
   $ teamsfx account set --subscription xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
   $ teamsfx provision

**Expected behavior**
I've expected successful messages. 

**Screenshots**
I've attached my error messages in *** Additional context ***

**VS Code Extension Information (please complete the following information):**
 - OS: Teams toolkit
 - Version 4.1.3

**CLI Information (please complete the following information):**
 - OS: windows10, WSL2, ubuntu 22, VSC,  node 16.13.1
 - Version: VSC 1.73.1

**Additional context**
The full error message follows:
```
$ teamsfx provision
? Select a resource group: XXX
? Azure account: xxxx@xxxx.com
Azure subscription: Azure subscription 1
M365 account: xxxx@xxxx.com

Cost may incur according to the usage. Do you want to provision resources in dev environment using accounts listed above?: Yes
████████████████████  100% | [2/2] Provisioning bot (✔) Done.  
████████████████████  100% | [1/1] Provision Teams app (✔) Done.  
████████████████████  98% / [1/1] Deploying ARM Templates: Deploying solution ARM templates to Azure. This could take several minutes.  
RestError: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.".
    at new RestError (/home/auser/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:10058808)
    at AzureAsyncOperationLROPollStrategy.LROPollStrategy.getRestError (/home/auser/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:9987637)
    at /home/auser/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:10002690
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'DeploymentFailed',
  statusCode: undefined,
  request: WebResource {
    streamResponseBody: undefined,
    url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585311151725493618?api-version=2021-01-01',
    method: 'GET',
    headers: HttpHeaders { _headersMap: [Object] },
    body: undefined,
    query: undefined,
    formData: undefined,
    withCredentials: false,
    abortSignal: undefined,
    timeout: 0,
    onUploadProgress: undefined,
    onDownloadProgress: undefined,
    proxySettings: undefined,
    keepAlive: undefined,
    agentSettings: undefined,
    redirectLimit: undefined,
    operationSpec: {
      httpMethod: 'PUT',
      path: 'subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/{deploymentName}',
      urlParameters: [Array],
      queryParameters: [Array],
      headerParameters: [Array],
      requestBody: [Object],
      responses: [Object],
      serializer: [Serializer]
    },
    operationResponseGetter: [Function: getOperationResponse]
  },
  response: {
    headers: HttpHeaders { _headersMap: [Object] },
    request: WebResource {
      streamResponseBody: undefined,
      url: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/resourcegroups/XXX/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585311151725493618?api-version=2021-01-01',
      method: 'GET',
      headers: [HttpHeaders],
      body: undefined,
      query: undefined,
      formData: undefined,
      withCredentials: false,
      abortSignal: undefined,
      timeout: 0,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      proxySettings: undefined,
      keepAlive: undefined,
      agentSettings: undefined,
      redirectLimit: undefined,
      operationSpec: [Object],
      operationResponseGetter: [Function: getOperationResponse]
    },
    status: 200,
    readableStreamBody: undefined,
    bodyAsText: `{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\\r\\n  \\"status\\": \\"Failed\\",\\r\\n  \\"error\\": {\\r\\n    \\"code\\": \\"ResourceDeploymentFailure\\",\\r\\n    \\"message\\": \\"The resource operation completed with terminal provisioning state 'Failed'.\\",\\r\\n    \\"details\\": [\\r\\n      {\\r\\n        \\"code\\": \\"DeploymentFailed\\",\\r\\n        \\"message\\": \\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\",\\r\\n        \\"details\\": [\\r\\n          {\\r\\n            \\"code\\": \\"Conflict\\",\\r\\n            \\"message\\": \\"{\\\\r\\\\n  \\\\\\"status\\\\\\": \\\\\\"Failed\\\\\\",\\\\r\\\\n  \\\\\\"error\\\\\\": {\\\\r\\\\n    \\\\\\"code\\\\\\": \\\\\\"ResourceDeploymentFailure\\\\\\",\\\\r\\\\n    \\\\\\"message\\\\\\": \\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\",\\\\r\\\\n    \\\\\\"details\\\\\\": [\\\\r\\\\n      {\\\\r\\\\n        \\\\\\"code\\\\\\": \\\\\\"DeploymentFailed\\\\\\",\\\\r\\\\n        \\\\\\"message\\\\\\": \\\\\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\\\\",\\\\r\\\\n        \\\\\\"details\\\\\\": [\\\\r\\\\n          {\\\\r\\\\n            \\\\\\"code\\\\\\": \\\\\\"BadRequest\\\\\\",\\\\r\\\\n            \\\\\\"message\\\\\\": \\\\\\"{\\\\\\\\r\\\\\\\\n  \\\\\\\\\\\\\\"error\\\\\\\\\\\\\\": {\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"code\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"InvalidBotData\\\\\\\\\\\\\\",\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"message\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"Bot is not valid. Errors: Microsoft App ID is required.  See https://docs.microsoft.com/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0 for detailed requirements.\\\\\\\\\\\\\\"\\\\\\\\r\\\\\\\\n  }\\\\\\\\r\\\\\\\\n}\\\\\\"\\\\r\\\\n          }\\\\r\\\\n        ]\\\\r\\\\n      }\\\\r\\\\n    ]\\\\r\\\\n  }\\\\r\\\\n}\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}"}]}}`,
    redirected: false,
    url: 'https://management.azure.com/subscriptions/xxxxxxxxxx-xxxx-xxxx-xxxx-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585311151725493618?api-version=2021-01-01',
    parsedBody: { status: 'Failed', error: [Object] }
  },
  body: {
    status: 'Failed',
    error: {
      code: 'DeploymentFailed',
      message: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.',
      details: [Array]
    }
  }
}
```

**Comment by IvanJobs** [comment]
Hi @tuxxon ,

I looked into the error messages closely. The root cause may be related to `botId`. I extracted the specific error messages out as below:
> Bot is not valid. Errors: Microsoft App ID is required.  See https://docs.microsoft.com/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0 for detailed requirements.

I didn't reproduce the error from my side. Can you tell me which version of TTK CLI you used to run `teamsfx provision`? 
You may run `teamsfx --version` to get the result.

**Comment by tuxxon** [comment]
Hello @IvanJobs 
```
$ teamsfx --version
1.0.5
```
Where running `teamsfx provision`, The following error is showed:
```
teamsfx provision
[TeamsfxCLI] Log in to your M365 account - opening default web browser at https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0&scope=https%3A%2F%2Fdev.teams.microsoft.com%2FAppDefinitions.ReadWrite%20openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A38101&client-request-id=4ee3c415-5f81-4f78-bc30-3ebbb3287a1b&response_mode=query&response_type=code&x-client-SKU=msal.js.node&x-client-VER=1.0.0-beta.6&x-client-OS=linux&x-client-CPU=x64&client_info=1&code_challenge=J-K78MAzREIa7GhRo5xu6xFQ8NLKRxlPD-CJjtMNl3s&code_challenge_method=S256&prompt=select_account# 
? Select a resource group: PFS
? Azure account: admin@jeisys1.onmicrosoft.com
Azure subscription: Azure subscription 1
M365 account: admin@jeisys1.onmicrosoft.com

Cost may incur according to the usage. Do you want to provision resources in dev environment using accounts listed above?: Yes
████████████████████  100% | [2/2] Provisioning bot (✔) Done.  
████████████████████  100% | [1/1] Provision Teams app (✔) Done.  
████████████████████  98% / [1/1] Deploying ARM Templates: Deploying solution ARM templates to Azure. This could take several minutes.  
RestError: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.".
    at new RestError (/home/tuxxon/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:10058808)
    at AzureAsyncOperationLROPollStrategy.LROPollStrategy.getRestError (/home/tuxxon/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:9987637)
    at /home/tuxxon/.nvm/versions/node/v16.13.1/lib/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:10002690
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'DeploymentFailed',
  statusCode: undefined,
  request: WebResource {
    streamResponseBody: undefined,
    url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585306168920945829?api-version=2021-01-01',
    method: 'GET',
    headers: HttpHeaders { _headersMap: [Object] },
    body: undefined,
    query: undefined,
    formData: undefined,
    withCredentials: false,
    abortSignal: undefined,
    timeout: 0,
    onUploadProgress: undefined,
    onDownloadProgress: undefined,
    proxySettings: undefined,
    keepAlive: undefined,
    agentSettings: undefined,
    redirectLimit: undefined,
    operationSpec: {
      httpMethod: 'PUT',
      path: 'subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/{deploymentName}',
      urlParameters: [Array],
      queryParameters: [Array],
      headerParameters: [Array],
      requestBody: [Object],
      responses: [Object],
      serializer: [Serializer]
    },
    operationResponseGetter: [Function: getOperationResponse]
  },
  response: {
    headers: HttpHeaders { _headersMap: [Object] },
    request: WebResource {
      streamResponseBody: undefined,
      url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585306168920945829?api-version=2021-01-01',
      method: 'GET',
      headers: [HttpHeaders],
      body: undefined,
      query: undefined,
      formData: undefined,
      withCredentials: false,
      abortSignal: undefined,
      timeout: 0,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      proxySettings: undefined,
      keepAlive: undefined,
      agentSettings: undefined,
      redirectLimit: undefined,
      operationSpec: [Object],
      operationResponseGetter: [Function: getOperationResponse]
    },
    status: 200,
    readableStreamBody: undefined,
    bodyAsText: `{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\\r\\n  \\"status\\": \\"Failed\\",\\r\\n  \\"error\\": {\\r\\n    \\"code\\": \\"ResourceDeploymentFailure\\",\\r\\n    \\"message\\": \\"The resource operation completed with terminal provisioning state 'Failed'.\\",\\r\\n    \\"details\\": [\\r\\n      {\\r\\n        \\"code\\": \\"DeploymentFailed\\",\\r\\n        \\"message\\": \\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\",\\r\\n        \\"details\\": [\\r\\n          {\\r\\n            \\"code\\": \\"Conflict\\",\\r\\n            \\"message\\": \\"{\\\\r\\\\n  \\\\\\"status\\\\\\": \\\\\\"Failed\\\\\\",\\\\r\\\\n  \\\\\\"error\\\\\\": {\\\\r\\\\n    \\\\\\"code\\\\\\": \\\\\\"ResourceDeploymentFailure\\\\\\",\\\\r\\\\n    \\\\\\"message\\\\\\": \\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\",\\\\r\\\\n    \\\\\\"details\\\\\\": [\\\\r\\\\n      {\\\\r\\\\n        \\\\\\"code\\\\\\": \\\\\\"DeploymentFailed\\\\\\",\\\\r\\\\n        \\\\\\"message\\\\\\": \\\\\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\\\\",\\\\r\\\\n        \\\\\\"details\\\\\\": [\\\\r\\\\n          {\\\\r\\\\n            \\\\\\"code\\\\\\": \\\\\\"BadRequest\\\\\\",\\\\r\\\\n            \\\\\\"message\\\\\\": \\\\\\"{\\\\\\\\r\\\\\\\\n  \\\\\\\\\\\\\\"error\\\\\\\\\\\\\\": {\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"code\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"InvalidBotData\\\\\\\\\\\\\\",\\\\\\\\r\\\\\\\\n    \\\\\\\\\\\\\\"message\\\\\\\\\\\\\\": \\\\\\\\\\\\\\"Bot is not valid. Errors: Microsoft App ID is required.  See https://docs.microsoft.com/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0 for detailed requirements.\\\\\\\\\\\\\\"\\\\\\\\r\\\\\\\\n  }\\\\\\\\r\\\\\\\\n}\\\\\\"\\\\r\\\\n          }\\\\r\\\\n        ]\\\\r\\\\n      }\\\\r\\\\n    ]\\\\r\\\\n  }\\\\r\\\\n}\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}"}]}}`,
    redirected: false,
    url: 'https://management.azure.com/subscriptions/4b25fd07-e17a-44e1-a33a-cd2fb702a386/resourcegroups/PFS/providers/Microsoft.Resources/deployments/teams_toolkit_deployment/operationStatuses/08585306168920945829?api-version=2021-01-01',
    parsedBody: { status: 'Failed', error: [Object] }
  },
  body: {
    status: 'Failed',
    error: {
      code: 'DeploymentFailed',
      message: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.',
      details: [Array]
    }
  }
}
```

**Comment by tuxxon** [comment]
By the way, It is working on macOS.

**Comment by tuxxon** [comment]
It's working well since upgrading to teamsfx v1.1.5.
(I mean it's not reproducing to me either.)
```
https://www.npmjs.com/package/@microsoft/teamsfx-cli
```

@IvanJobs 
Thank you for noticing me about teamsfx version
