### ISSUE TITLE
Starting today, newly created Teams Tab app in VS throwing error

### ISSUE THREAD

**Issue by JTHouck** [OfficeDev/TeamsFx#7409]
**Describe the bug**
I have been using the Teams Toolkit in Visual Studio to build a custom Tab application using Blazor Server. I updated Visual Studio 2022 today to the latest version, created a new Teams tab app project, clicked on Teams Toolkit --> Prepare Teams App Dependencies. The task completed successfully, but when I hit F5 to run the application, a browser opens to Microsoft teams and I can select a chat to add the app too. Once the tab configuration page shows, I get this error in the console:

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot set properties of undefined (setting 'microsoftTeams')
TypeError: Cannot set properties of undefined (setting 'microsoftTeams')
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:221
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:226
      Microsoft.JSInterop.JSException: Cannot set properties of undefined (setting 'microsoftTeams')
TypeError: Cannot set properties of undefined (setting 'microsoftTeams')
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:221
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:226
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.ImportModuleAsync() in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 36
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.InvokeVoidAsync(String functionName, Object[] args) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 20
         at WideOrbitTeamsApp_MeetingSlate.Pages.TabConfig.OnAfterRenderAsync(Boolean firstRender) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Pages\TabConfig.razor:line 29
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'c3VGQcFp1P-a5mwUFo-i5e0b2rqmh1-xT_Iw-DIqbE8'.
      Microsoft.JSInterop.JSException: Cannot set properties of undefined (setting 'microsoftTeams')
TypeError: Cannot set properties of undefined (setting 'microsoftTeams')
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:221
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:226
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.ImportModuleAsync() in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 36
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.InvokeVoidAsync(String functionName, Object[] args) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 20
         at WideOrbitTeamsApp_MeetingSlate.Pages.TabConfig.OnAfterRenderAsync(Boolean firstRender) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Pages\TabConfig.razor:line 29
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot set properties of undefined (setting 'microsoftTeams')
TypeError: Cannot set properties of undefined (setting 'microsoftTeams')
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:221
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:226
      Microsoft.JSInterop.JSException: Cannot set properties of undefined (setting 'microsoftTeams')
TypeError: Cannot set properties of undefined (setting 'microsoftTeams')
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:221
    at https://unpkg.com/@microsoft/teams-js@2.7.0/dist/MicrosoftTeams.min.js:1:226
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.ImportModuleAsync() in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 36
         at WideOrbitTeamsApp_MeetingSlate.Interop.InteropModuleBase.InvokeVoidAsync(String functionName, Object[] args) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Interop\InteropModuleBase.cs:line 20
         at WideOrbitTeamsApp_MeetingSlate.Pages.TabConfig.OnAfterRenderAsync(Boolean firstRender) in C:\Users\jhouck\source\repos\WOTeamsMeetingAppSlate\WideOrbitTeamsApp_MeetingSlate\WideOrbitTeamsApp_MeetingSlate\Pages\TabConfig.razor:line 29
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**To Reproduce**
1. Update Visual Studio 2022 to latest version (17.4.3)
2. Make sure Teams Toolkit is installed in the same VS installation
3. Create a new Teams Tab app project using Visual Studio 
4. Select the project from the solution window (right click) --> Teams Toolkit --> Prepare Teams App Dependencies
5. Save project/solution
6. Press F5/run project in debug mode
7. Wait for browser to open to MS teams, select add app to Chat and then select a chat to add the app to
8. When the default tab configuration page loads, you will see a generic error message with a prompt to reload the app
9. The error message above will be displayed in the output/console window

**Expected behavior**
The default generated app from the template will load into the selected chat without error

**Screenshots**
[image](https://user-images.githubusercontent.com/122044089/210842312-b376e9a5-1033-4d7a-94fc-1086109f2040.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 
 - Version 10 build: 19045.2364

**CLI Information (please complete the following information):**

**Additional context**
Note that this problem started today and was working as expected yesterday

**Comment by yiqing-zhao** [comment]
Hello @JTHouck, we believe that this is due to the webpack change from Teams-JS side. See https://github.com/OfficeDev/microsoft-teams-library-js/issues/1506 for more information. 

Teams-JS team has released @microsoft/teams-js 2.7.1 several days ago, and should solve the issue.
