### ISSUE TITLE
Teams toolkit crashes on F5 node 18.3.0

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsFx#7661]
Teams toolkit crashes when running on nodejs version 18.3.0
OS: macOS Ventura 13.1

Affected IDE: VSCode
Affected IDE Version: 1.75.0 (universal)
Affected Toolkit Version: v4.2.1

Steps : View samples, create from hello world bot, F5

On debug the app crashes

In the logs:

Executing task: npm run dev:teamsfx

 

 

> echobot@1.0.0 dev:teamsfx

> env-cmd --silent -f .env.teamsfx.local npm run dev

 

 

> echobot@1.0.0 dev

> nodemon --watch ./src --exec node --inspect=9239 --signal SIGINT -r ts-node/register ./index.ts

 

[nodemon] 2.0.20

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): src

[nodemon] watching extensions: ts,json

[nodemon] starting `node --inspect=9239 -r ts-node/register ./index.ts`

Debugger listening on ws://127.0.0.1:9239/2a7d11a8-64c4-49ab-9a42-f12dc7dc0f26

For help, see: https://nodejs.org/en/docs/inspector

/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/request.js:848

    Request.prototype.closed = function closed() {

                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter

    at patch (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/request.js:848:30)

    at Object.<anonymous> (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/server.js:33:1)

    at Module._compile (node:internal/modules/cjs/loader:1218:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

    at Object.require.extensions.<computed> [as .js] (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/ts-node/src/index.ts:1608:43)

    at Module.load (node:internal/modules/cjs/loader:1081:32)

    at Function.Module._load (node:internal/modules/cjs/loader:922:12)

    at Module.require (node:internal/modules/cjs/loader:1105:19)

    at require (node:internal/modules/cjs/helpers:103:18)

    at Object.<anonymous> (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/index.js:10:14)

[nodemon] app crashed - waiting for file changes before starting...

 *  Terminal will be reused by tasks, press any key to close it.

 

 *  Executing task: npm run dev:teamsfx

 

 

> echobot@1.0.0 dev:teamsfx

> env-cmd --silent -f .env.teamsfx.local npm run dev

 

 

> echobot@1.0.0 dev

> nodemon --watch ./src --exec node --inspect=9239 --signal SIGINT -r ts-node/register ./index.ts

 

[nodemon] 2.0.20

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): src

[nodemon] watching extensions: ts,json

[nodemon] starting `node --inspect=9239 -r ts-node/register ./index.ts`

Debugger listening on ws://127.0.0.1:9239/108ed108-9fd9-45e0-a30a-ae52aad557be

For help, see: https://nodejs.org/en/docs/inspector

/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/request.js:848

    Request.prototype.closed = function closed() {

                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter

    at patch (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/request.js:848:30)

    at Object.<anonymous> (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/server.js:33:1)

    at Module._compile (node:internal/modules/cjs/loader:1218:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

    at Object.require.extensions.<computed> [as .js] (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/ts-node/src/index.ts:1608:43)

    at Module.load (node:internal/modules/cjs/loader:1081:32)

    at Function.Module._load (node:internal/modules/cjs/loader:922:12)

    at Module.require (node:internal/modules/cjs/loader:1105:19)

    at require (node:internal/modules/cjs/helpers:103:18)

    at Object.<anonymous> (/Users/pat/TeamsApps/hello-world-bot/bot/node_modules/restify/lib/index.js:10:14)

[nodemon] app crashed - waiting for file changes before starting...

**Comment by XiaofuHuang** [comment]
Thank you for contacting us! 
The TeamsFx will support node 18 in the next release. Currently, you can manually upgrade the sample to support node 18 through the following steps:
1.  Update `restify` in `hello-world-bot/bot/package.json`
     ```
      "dependencies": {
          "restify": "^10.0.0"
      },
      "devDependencies": {
          "@types/restify": "8.5.5"
     }
     ```
2. Update `compilerOptions.target` in `hello-world-bot/bot/tsconfig.json`
    ```
    {
        "compilerOptions": {
            "target": "es2017"
        }
    }
    ```

**Comment by denlai-mshk** [comment]
Currently, I'm using Teams Toolkit Prerelease v4.99 (aka v5.0)
The template project created by the Teams Toolkit already incorporated with 
`
restify in hello-world-bot/bot/package.json

"dependencies": {
     "restify": "^10.0.0"
 },
 "devDependencies": {
     "@types/restify": "8.5.5"
}`

and
`
compilerOptions.target in hello-world-bot/bot/tsconfig.json
{
    "compilerOptions": {
        "target": "es2017"
    }
}
`
However, this nodemon app crashed still happens

`
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `node --inspect=9239 -r ts-node/register ./index.ts`
Debugger listening on ws://127.0.0.1:9239/706cd51f-6316-4017-93ca-c1827a1fb90c
For help, see: https://nodejs.org/en/docs/inspector
C:\CodeProject\TeamsGPT\bot-sso\node_modules\azure-openai\dist\configuration.js:41
                throw new Error("Azure Configuration requires apiKey, endpoint");
                      ^
Error: Azure Configuration requires apiKey, endpoint
    at new Configuration (C:\CodeProject\TeamsGPT\bot-sso\node_modules\azure-openai\dist\configuration.js:41:23)
    at new TeamsBot (C:\CodeProject\TeamsGPT\bot-sso\teamsBot.ts:46:27)
    at Object.<anonymous> (C:\CodeProject\TeamsGPT\bot-sso\index.ts:56:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (C:\CodeProject\TeamsGPT\bot-sso\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (C:\CodeProject\TeamsGPT\bot-sso\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[nodemon] app crashed - waiting for file changes before starting...
`
Any advice? thanks.
