### ISSUE TITLE
unknown.SyntaxError when having escaped apostrophe in manifest file

### ISSUE THREAD

**Issue by ninob** [OfficeDev/TeamsFx#8224]
**Describe the bug**
When building Teams app package, JSON.parse  is not correctly handling escaping of apostrophe in manifest. 

**To Reproduce**
1. Set short description in manifest to "Without our app, it\\'s just boring"
2. Select Zip Teams app package from Teams Toolkit 
3. See error:

[2023-03-30T20:00:23.677Z] [Error] - code:unknown.SyntaxError, message: Unexpected token & in JSON at position 617, stack: SyntaxError: Unexpected token & in JSON at position 617
	at JSON.parse (<anonymous>)
	at ManifestUtils.getManifest (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7483800)
	at async Object.buildTeamsAppPackage (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7409574)
	at async AppManifest.build (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7392051)
	at async AppManifest.<anonymous> (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:6755649)
	at async FxCore.executeUserTaskOld (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7768618)
	at async FxCore.<anonymous> (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7912245)
	at async exports.ProjectSettingsWriterMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7988501)
	at async exports.ContextInjectorMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7900697)
	at async FxCore.<anonymous> (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7907698)
	at async exports.VideoFilterAppBlockerMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:8068227)
	at async exports.ProjectSettingsLoaderMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7986948)
	at async exports.ProjectVersionCheckerMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7992488)
	at async exports.AadManifestMigrationMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7880258)
	at async exports.ProjectConsolidateMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7900409)
	at async exports.ProjectMigratorMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7949042)
	at async exports.ConcurrentLockerMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7882921)
	at async exports.ErrorHandlerMW (c:\Users\<REDACTED>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-4.2.4\out\src\extension.js:2:7913698)

**Expected behavior**
Expect JSON.parse to correctly escape the apostrophe.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 (10.0.22000.1696)
 - Version 4.2.4

**CLI Information (please complete the following information):**
 - OS: Windows 11 (10.0.22000.1696)
 - Version 1.1.5

**Additional context**
Escaping newline  (e.g., \\n  )  in the manifest works fine.

**Comment by nliu-ms** [comment]
Hey @ninob , thanks for reporting this issue. Yes I can reproduce the error.

Can you please try the following string without 2 backslashes? Then the template will be rendered correctly. Thanks!
![image](https://user-images.githubusercontent.com/71362691/229680936-2753d0f9-8ba0-4e79-a0e6-cc826d13e506.png)

![image](https://user-images.githubusercontent.com/71362691/229681143-8a21558b-96b5-4638-b2a0-29de4c8a088f.png)

**Comment by ninob** [comment]
Hello  I am traveling without access to this dev environment until Monday, April 10; will try suggested steps then and reply.

**Comment by nliu-ms** [comment]
Thanks for letting me know your schedule @ninob

**Comment by ninob** [comment]
Hello - In both cases the output is as below: 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/1406633/230903613-2bde9669-a44a-4ff3-aec7-1957116bd5b1.png">

**Comment by nliu-ms** [comment]
Hey @ninob, you need to both update manifest.template.json with triple {}, and config.dev.json file, like below:
![image](https://user-images.githubusercontent.com/71362691/231062752-9b296b55-cd5c-4118-9d48-ad7100f1a787.png)

Only update one of them won't get expected result. 

If it still doesn't work, can you please provide your Teams Toolkit version? I'm using v4.2.4. Thanks!

**Comment by nliu-ms** [comment]
Awesome! I will close this issue then.
