### ISSUE TITLE
teamsApp/extendToM365 fails when running in Codespaces

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#8703]
**Describe the bug**
Running a sample that has teamsApp/extendToM365 in the teamsapp.local.yml fails with this error:

```
[Error] - code:Core.Error, message: {"message":"Request failed with status code 401","detail":"\"Jwks remote fetch is failed\"","tracingId":""}
stack: Error: {"message":"Request failed with status code 401","detail":"\"Jwks remote fetch is failed\"","tracingId":""}
    at createError (/home/node/.vscode-remote/extensions/teamsdevapp.ms-teams-vscode-extension-4.99.2023041408/out/src/extension.js:8:302204)
    at settle (/home/node/.vscode-remote/extensions/teamsdevapp.ms-teams-vscode-extension-4.99.2023041408/out/src/extension.js:8:306486)
    at IncomingMessage.handleStreamEnd (/home/node/.vscode-remote/extensions/teamsdevapp.ms-teams-vscode-extension-4.99.2023041408/out/src/extension.js:8:291785)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The same project runs OK when debugging locally. However, I had to make changes to the .vscode files to run in Codespaces, but those changes (ports, etc.) appear to be unrelated to this issue. 

**VS Code Extension Information (please complete the following information):**
 - OS: Codespaces
 - v4.99.2023041408

**Comment by swatDong** [comment]
This is an intermittent issue caused by upstream service. Already reported to upstream team and waiting for the fix.

For workaround, retry may help.
Or, if you do not change your manifest file, you can temporarily comment out the `teamsApp/extendToM365` to skip the step in next run.

**Comment by wh-alice** [comment]
Close stale issues. Please create new issue then we can support.
