### ISSUE TITLE
[BUG] TeamsFx 2.0.0 - Consent check now fails.

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#8734]
**Describe the bug**
For some reason loginasync now tries to connect to its own app name which redirects to my own page code.
![image](https://github.com/OfficeDev/TeamsFx/assets/117128832/319b4152-6f19-4ada-ad85-b342b704f86a)

**To Reproduce**
Try to connect to the microsoft graph with a new test Azure AD user and a published version of a team's app.
Code to consent check:
```
static internal async Task<bool> ConsentCheck(TeamsUserCredential teamsUserCredential, string[] scope, TokenHandler.AsUser UseUserDelegatedToken)
        {
            try
            {
                await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
                return true;
            }
            catch (ExceptionWithCode e)
            {
                if (e.Code == ExceptionCode.UiRequiredError)
                {
                    await teamsUserCredential.LoginAsync(scope); // <--- this appears to be the problem.
                    await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
                    return true;
                }
                else return false;

            }
        }
```
scope i'm using:
internal static readonly string[] UserReadWrite = new[] { "https://graph.microsoft.com/User.ReadWrite" };

Login Async =:
```
// Remarks:
        //     Only works in Teams client app. User will be redirected to the authorization
        //     page to login and consent.
        public async Task LoginAsync(string scopes)
        {
            _logger.LogInformation("Popup consent page to get user's access token with scopes: " + scopes);
            await EnsureTeamsSdkInitialized().ConfigureAwait(continueOnCapturedContext: false);
            try
            {
                IJSObjectReference jsObjectReference = await _teamsSdkTask.Value.ConfigureAwait(continueOnCapturedContext: false);
                DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(17, 3);
                defaultInterpolatedStringHandler.AppendFormatted(_authenticationOptions.InitiateLoginEndpoint);
                defaultInterpolatedStringHandler.AppendLiteral("?clientId=");
                defaultInterpolatedStringHandler.AppendFormatted(_authenticationOptions.ClientId);
                defaultInterpolatedStringHandler.AppendLiteral("&scope=");
                defaultInterpolatedStringHandler.AppendFormatted(WebUtility.UrlEncode(scopes));
                string text = defaultInterpolatedStringHandler.ToStringAndClear();
                if (string.IsNullOrEmpty(await JSObjectReferenceExtensions.InvokeAsync<string>(jsObjectReference, "authenticate", new object[1] { text }).ConfigureAwait(continueOnCapturedContext: false)))
                {
                    string message = "Get empty authentication result from Teams";
                    _logger.LogError(message);
                    throw new ExceptionWithCode(message, ExceptionCode.InternalError);
                }
            }
            catch (JSException ex)
            {
                string message2 = "Consent failed for the scope " + scopes + " with error: " + ex.Message;
                _logger.LogError(message2);
                throw new ExceptionWithCode(message2, ExceptionCode.ConsentFailed);
            }
        }
```

**Expected behavior**
should pop up the standard login consent check by microsoft

**VS Code Extension Information (please complete the following information):**
Nuget Microsoft.TeamsFx 2.0.0
VS C# 2022 17.5.5

**Additional context**
If you try to run this inside of teams only, it just loops a loading screen forever. No consent checks ever happen. Even if it did work, this absolutely must be possible to work on the teams.microsoft.com web version as well.

**Comment by wrharper-AASP** [comment]
This has worked previously, I'm not sure why the issue would change. This must be some new issue with the Microsoft Graph changes and it is now breaking the consent check to TeamsFx?

**Comment by wrharper-AASP** [comment]
I have captured the error in Teams:
```
Microsoft.TeamsFx.ExceptionWithCode: Consent failed for the scope https://graph.microsoft.com/User.ReadWrite with error: This call is only allowed in following contexts: ["content","sidePanel","settings","remove","task","stage","meetingStage"]. Current context: "authentication".
Error: This call is only allowed in following contexts: ["content","sidePanel","settings","remove","task","stage","meetingStage"]. Current context: "authentication".
    at ue (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:1:18701)
    at e.authenticate (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:1:24301)
    at Module.authenticate (https://localhost:44302/_content/Microsoft.TeamsFx/jsInterop.js:9:42)
    at https://localhost:44302/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:44302/_framework/blazor.server.js:1:3475)
    at https://localhost:44302/_framework/blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:44302/_framework/blazor.server.js:1:72063)
    at kt._processIncomingData (https://localhost:44302/_framework/blazor.server.js:1:70105)
```

**Comment by SLdragon** [comment]
Hi, @wrharper-AASP , here is an issue that may related to your error, you can take a look:
https://github.com/OfficeDev/microsoft-teams-library-js/issues/275

This error happens when you're calling authenticate() to open an auth popup, but the page calling it is already in an auth popup.

Maybe the code below caused the issue.

```cs
static internal async Task<bool> ConsentCheck(TeamsUserCredential teamsUserCredential, string[] scope, TokenHandler.AsUser UseUserDelegatedToken)
        {
            try
            {
                await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
                return true;
            }
            catch (ExceptionWithCode e)
            {
                if (e.Code == ExceptionCode.UiRequiredError)
                {
                    await teamsUserCredential.LoginAsync(scope); // <--- this appears to be the problem.
                    await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
                    return true;
                }
                else return false;

            }
        }
```

For best practice, you need to have a button to trigger consent flow, and your ConsentCheck function should only check the stauts as below:

```cs
static internal async Task<bool> ConsentCheck(TeamsUserCredential teamsUserCredential, string[] scope, TokenHandler.AsUser UseUserDelegatedToken)
        {
            try
            {
                await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
                return true;
            }
            catch (ExceptionWithCode e)
            {
                if (e.Code == ExceptionCode.UiRequiredError)
                {
                    return true;
                }
                else return false;

            }
        }
```

**Comment by wrharper-AASP** [comment]
> Hi, @wrharper-AASP , here is an issue that may related to your error, you can take a look: [OfficeDev/microsoft-teams-library-js#275](https://github.com/OfficeDev/microsoft-teams-library-js/issues/275)
> 
> This error happens when you're calling authenticate() to open an auth popup, but the page calling it is already in an auth popup.
> 
> Maybe the code below caused the issue.
> 
> ```cs
> static internal async Task<bool> ConsentCheck(TeamsUserCredential teamsUserCredential, string[] scope, TokenHandler.AsUser UseUserDelegatedToken)
>         {
>             try
>             {
>                 await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
>                 return true;
>             }
>             catch (ExceptionWithCode e)
>             {
>                 if (e.Code == ExceptionCode.UiRequiredError)
>                 {
>                     await teamsUserCredential.LoginAsync(scope); // <--- this appears to be the problem.
>                     await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
>                     return true;
>                 }
>                 else return false;
> 
>             }
>         }
> ```
> 
> For best practice, you need to have a button to trigger consent flow, and your ConsentCheck function should only check the stauts as below:
> 
> ```cs
> static internal async Task<bool> ConsentCheck(TeamsUserCredential teamsUserCredential, string[] scope, TokenHandler.AsUser UseUserDelegatedToken)
>         {
>             try
>             {
>                 await UseUserDelegatedToken.GetToken(teamsUserCredential, scope);
>                 return true;
>             }
>             catch (ExceptionWithCode e)
>             {
>                 if (e.Code == ExceptionCode.UiRequiredError)
>                 {
>                     return true;
>                 }
>                 else return false;
> 
>             }
>         }
> ```

This is called on firstrender and does need to be automated. There would be no button for this.

**Comment by wrharper-AASP** [comment]
I may have found the solution a little further down. https://github.com/OfficeDev/TeamsFx/blob/dev/packages/dotnet-sdk/README.md
Upgrade from 1.x.x to 2.0.0
I'll go through this and keep everyone posted. It is because of Microsoft.Graph like I suspected.

**Comment by wrharper-AASP** [comment]
ok i am mostly there but https://localhost/auth-start.html isn't right. what is the port for Teams local host or in general what is the tab endpoint when testing locally?
![image](https://github.com/OfficeDev/TeamsFx/assets/117128832/12208765-4b27-4033-ad93-f52d26a9dffd)

**Comment by wrharper-AASP** [comment]
got it! "InitiateLoginEndpoint": "https://localhost:44302/auth-start.html", //New Line
![image](https://github.com/OfficeDev/TeamsFx/assets/117128832/2a5696ce-cf26-41b4-a9c5-c8640e73d41d)

**Comment by wrharper-AASP** [comment]
ok the only problem that is left is the biceps are not nearly the same structure as the notes for the readme.md
Does anyone have a visual studio 2022 working in production bicep files that i can look at? i need to see azureWebAppTabConfig.bicep & azureWebAppTab.bicep.

**Comment by wrharper-AASP** [comment]
ok, this new issue may be related to: https://github.com/OfficeDev/TeamsFx/issues/7901

**Comment by wrharper-AASP** [comment]
fixed
use:
TeamsFx__Authentication__InitiateLoginEndpoint: '${webappEndpoint}/auth-start.html'
instead of:
TeamsFx__Authentication__InitiateLoginEndpoint: 'https://${webApp.properties.defaultHostName}/auth-start.html'
in azureWebAppTabConfig.bicep

the readme.md instructions are quite wrong in this case. here are the bicep files and appsettings.json in case anyone else runs into this same problem!
Templates\appPackage\teamsfx\azureWebApPTabConfig.bicep:
```
// Auto generated content, please customize files under provision folder

@secure()
param provisionParameters object
param provisionOutputs object
@secure()
param currentAppSettings object

var webAppName = split(provisionOutputs.azureWebAppTabOutput.value.resourceId, '/')[8]
var webappEndpoint = provisionOutputs.azureWebAppTabOutput.value.siteEndpoint
var m365ClientId = provisionParameters['m365ClientId']
var m365ClientSecret = provisionParameters['m365ClientSecret']
var m365TenantId = provisionParameters['m365TenantId']
var m365OauthAuthorityHost = provisionParameters['m365OauthAuthorityHost']
var m365ApplicationIdUri = 'api://${ provisionOutputs.TabOutput.value.domain }/${m365ClientId}'

resource webAppSettings 'Microsoft.Web/sites/config@2021-02-01' = {
  name: '${webAppName}/appsettings'
  properties: union({
    TeamsFx__Authentication__ClientId: m365ClientId // Client id of AAD application
    TeamsFx__Authentication__ClientSecret: m365ClientSecret // Client secret of AAD application
    TeamsFx__Authentication__InitiateLoginEndpoint: '${webappEndpoint}/auth-start.html'
    TeamsFx__Authentication__OAuthAuthority: uri(m365OauthAuthorityHost, m365TenantId) // AAD authority host
    TAB_APP_ENDPOINT: webappEndpoint
    IDENTITY_ID: provisionOutputs.identityOutput.value.identityClientId // User assigned identity id, the identity is used to access other Azure resources
  }, currentAppSettings)
}
```

Templates\appPackage\azure\provision\azureWebAppTab.bicep:
```
@secure()
param provisionParameters object
param userAssignedIdentityId string

var resourceBaseName = provisionParameters.resourceBaseName
var serverfarmsName = contains(provisionParameters, 'webAppServerfarmsName') ? provisionParameters['webAppServerfarmsName'] : '${resourceBaseName}tab' // Try to read name for App Service Plan from parameters
var webAppSKU = contains(provisionParameters, 'webAppSKU') ? provisionParameters['webAppSKU'] : 'F1' // Try to read SKU for Azure Web App from parameters
var webAppName = contains(provisionParameters, 'webAppSitesName') ? provisionParameters['webAppSitesName'] : '${resourceBaseName}tab' // Try to read name for Azure Web App from parameters

// Compute resources for your Web App
resource serverfarm 'Microsoft.Web/serverfarms@2021-02-01' = {
  kind: 'app'
  location: resourceGroup().location
  name: serverfarmsName
  sku: {
    name: webAppSKU
  }
  properties: {}
}

// Web App that hosts your app
resource webApp 'Microsoft.Web/sites@2021-02-01' = {
  kind: 'app'
  location: resourceGroup().location
  name: webAppName
  properties: {
    serverFarmId: serverfarm.id
    keyVaultReferenceIdentity: userAssignedIdentityId // Use given user assigned identity to access Key Vault
    httpsOnly: true
    siteConfig: {
      appSettings: [
        {
          name: 'WEBSITE_RUN_FROM_PACKAGE'
          value: '1'
        }
      ]
    }
  }
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedIdentityId}': {} // The identity is used to access other Azure resources
    }
  }
}

output skuName string = webAppSKU
output siteName string = webAppName
output domain string = webApp.properties.defaultHostName
output appServicePlanName string = serverfarmsName
output resourceId string = webApp.id
output siteEndpoint string = 'https://${webApp.properties.defaultHostName}'
```

appsettings.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "TeamsFx": {
    "Authentication": {
      "ClientId": "$clientId$",
      "ClientSecret": "$client-secret$",
      "InitiateLoginEndpoint": "$TAB_APP_ENDPOINT$/auth-start.html", //New Line
      "OAuthAuthority": "$oauthAuthority$"
    }
  }
}
```
in appsettings.Development.json just add the 
      "InitiateLoginEndpoint": "https://localhost:44302/auth-start.html", //New Line

the readme is right for the auth-start/auth-end, just follow it for that part.

now MSGraph needs to be fixed:
```
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Users.Item.Extensions.ExtensionsRequestBuilder.PostAsync(Extension body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

both of these attempts no longer work:
```
try
{
    await gs.Users[userid].Extensions[Globals.ExtensionName].PatchAsync(extension);
}
catch
{
    await gs.Users[userid].Extensions.PostAsync(extension);
}
```
you'll use gs.me instead which creates another new error:
```
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Extensions.ExtensionsRequestBuilder.PostAsync(Extension body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

**Comment by wrharper-AASP** [comment]
Ok it looks like you can't post no matter what now. How is this possible with the new changes?

Same error with just:
```
OpenTypeExtension extension = new()
            {
                Id = "test",
                ExtensionName = "testname",
                AdditionalData = new Dictionary<string, object>
                {
                    { "test", "test" }
                }
            };
```

**Comment by wrharper-AASP** [comment]
it turns out Microsoft has changed how this works without telling anyone. You have to define the extension object while doing the post at the same time now.

**it is yet another "unwritten rule" created out of nowhere....**

this:
```
Extension extension = new()
                {

                    Id = "test",
                    OdataType = "microsoft.graph.openTypeExtension",
                    AdditionalData = new Dictionary<string, object>
                    {
                        { "test", "test" },
                    }
                });
try
            {
                //await gs.Users[userid].Extensions[Globals.ExtensionName].PatchAsync(extension);
                await gs.Me.Extensions[Globals.ExtensionName].PatchAsync(extension);
            }
            catch
            {
                //await gs.Users[userid].Extensions.PostAsync(extension);
                await gs.Me.Extensions.PostAsync(extension);
            } 

```
must now work like this:
```
try
            {
                //await gs.Users[userid].Extensions[Globals.ExtensionName].PatchAsync(extension);
                await gs.Me.Extensions[Globals.ExtensionName].PatchAsync(new()
                {

                    Id = "test",
                    OdataType = "microsoft.graph.openTypeExtension",
                    AdditionalData = new Dictionary<string, object>
                    {
                        { "test", "test" },
                    }
                });
            }
            catch
            {
                //await gs.Users[userid].Extensions.PostAsync(extension);
                await gs.Me.Extensions.PostAsync(new()
                {

                    Id = "test",
                    OdataType = "microsoft.graph.openTypeExtension",
                    AdditionalData = new Dictionary<string, object>
                    {
                        { "test", "test" },
                    }
                });
            } 
```
for whatever reason they are forcing everyone to now define the object during the call. if you try to define it before hand it won't work anymore. It is the exact same thing, and you can work this way in all of C# but not at this one specific object for some reason.
They are doing really weird in memory checks... funny since you have to create all the variables beforehand anyway somewhere at some point. so they are still in memory... what a strange concept. I'll be emailing security@microsoft.com at this point. It looks like this issue is finally fixed now though.

**Comment by wrharper-AASP** [comment]
confirmed this is now working locally and published.
