### ISSUE TITLE
Cannot connect to existing single tenant bot: 'MsaAppTenantId' property cannot be changed.. 

### ISSUE THREAD

**Issue by Radiergummi** [OfficeDev/TeamsFx#8774]
**Describe the bug**
I'm trying to have a local development app configuration using a singleTenant app, because that matches our production environment. This seems to cause trouble. During automatic provisioning, I get the error below.

**To Reproduce**
1. Create a singleTenant bot on dev.botframework.com
2. Set the bot ID in the local environment config
3. Start the preview debugging

**Expected behavior**
Expected the deployment to just work.

**Error**
```
[2023-05-23T16:25:36.330Z] [Info] - Failed to Execute lifecycle provision due to failed action: botFramework/create. DeveloperPortalAPIFailed:API call to Developer Portal failed: Error, Request failed with status code 400, API name: update-bot, X-Correlation-ID: 2e6ad175-f2ed-44bd-b274-d854ee150450. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "'MsaAppTenantId' property cannot be changed.. ". Env output: {"TEAMS_APP_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","TEAMS_APP_TENANT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","BOT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","SECRET_BOT_PASSWORD":"******"}
```

**VS Code Extension Information (please complete the following information):**
 - Version [e.g. 22] 2.0.0

**CLI Information (please complete the following information):**
 - OS: [e.g. iOS8.1] MacOS
 - Version [e.g. 22] 13.3.1

**Additional context**
<details>
<summary>Full Log</summary>

<pre>
[2023-05-23T16:24:58.936Z] [Info] - Running 'Validate prerequisites' Visual Studio Code task.

(Total: 3 Steps) Teams Toolkit is checking the required prerequisites.

(1/3) Checking Node.js ...
(2/3) Checking Microsoft 365 Account ...
(3/3) Checking ports occupancy ...

Summary:

(√) Done: Node.js version (v19.6.1) is installed 
(√) Done: Microsoft 365 Account (moritz@matchory.com) is logged in and sideloading permission is enabled 
(√) Done: Ports (53000, 3978, 9239) are not occupied 

Visit https://aka.ms/teamsfx-tasks/check-prerequisites to learn more about 'Validate prerequisites' task.

[2023-05-23T16:24:59.911Z] [Info] - Finished 'Validate prerequisites' Visual Studio Code task in 1.00 seconds.
[2023-05-23T16:24:59.950Z] [Info] - Visual Studio Code-Task wird ausgeführt: „Lokalen Tunnel starten“

(Total: 1 Step) Das Teams-Toolkit startet den lokalen Tunneldienst, um die öffentliche URL an den lokalen Port weiterzuleiten und den Datenverkehr zu untersuchen. Öffnen Sie das Terminalfenster, um die Details anzuzeigen.

(1/1) Der Dev-Tunneldienst wird gestartet. ... 

Zusammenfassung:

(√) Done: URL https://xxxxxxxx-xxxx.euw.devtunnels.ms/ wird an http://localhost:3978 weitergeleitet. [BOT_DOMAIN, BOT_ENDPOINT] wurde in /Users/moritz/Projects/matchory-bot/env/.env.local gespeichert.

Besuchen Sie https://aka.ms/teamsfx-local-tunnel-task, um weitere Informationen zum Task „Lokalen Tunnel starten“ zu erhalten.

[2023-05-23T16:25:00.974Z] [Info] - Der lokale Tunneldienst wurde in 1.03 Sekunden gestartet.
[2023-05-23T16:25:01.254Z] [Info] - Executing app registration and provision 

Lebenszyklusstufe: provision(10 Schritt(e) insgesamt). Die folgenden Aktionen werden ausgeführt: 
(1/10) Aktion aadApp/create: Azure Active Directory-App zum Authentifizieren von Benutzern erstellen
(2/10) Aktion teamsApp/create: Erstellen Sie eine Teams-App.
(3/10) Aktion botAadApp/create: Erstellen Sie einen neuen Bot, oder verwenden Sie einen vorhandenen Bot der Azure Active Directory-Anwendung wieder.
(4/10) Aktion botFramework/create: Erstellt oder aktualisiert die Bot-Registrierung auf „dev.botframework.com“
(5/10) Aktion script
(6/10) Aktion aadApp/update: Azure Active Directory-App-Manifest auf eine vorhandene App anwenden
(7/10) Aktion teamsApp/validateManifest: Validieren Sie eine Teams-App.
(8/10) Aktion teamsApp/zipAppPackage: Erstellen Sie ein Teams-App-Paket.
(9/10) Aktion teamsApp/validateAppPackage: Validieren Sie eine Teams-App.
(10/10) Aktion teamsApp/update: Aktualisieren Sie eine Teams-App..

[2023-05-23T16:25:01.257Z] [Info] - Executing lifecycle provision
[2023-05-23T16:25:01.257Z] [Info] - Executing action aadApp/create in lifecycle provision
[2023-05-23T16:25:01.261Z] [Info] - Die Aktion aadApp/create wird ausgeführt
[2023-05-23T16:25:01.261Z] [Info] - Die Umgebungsvariable „AAD_APP_CLIENT_ID“ ist bereits vorhanden und überspringt Schritt zum Generieren der neuen Azure Active Directory-App.
[2023-05-23T16:25:01.261Z] [Info] - Die Umgebungsvariable „SECRET_AAD_APP_CLIENT_SECRET“ ist bereits vorhanden und überspringt Schritt zum Generieren der neuen Azure Active Directory-App.
[2023-05-23T16:25:01.261Z] [Info] - Die aadApp/create-Aktion wurde erfolgreich ausgeführt.
[2023-05-23T16:25:01.264Z] [Info] - Action aadApp/create in lifecycle provision succeeded with output {}
[2023-05-23T16:25:01.264Z] [Info] - Executing action teamsApp/create in lifecycle provision
[2023-05-23T16:25:01.479Z] [Info] - Action teamsApp/create in lifecycle provision succeeded with output {"TEAMS_APP_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","TEAMS_APP_TENANT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
[2023-05-23T16:25:01.479Z] [Info] - Executing action botAadApp/create in lifecycle provision
[2023-05-23T16:25:01.482Z] [Info] - Die Aktion botAadApp/create wird ausgeführt
[2023-05-23T16:25:01.483Z] [Info] - Es wurde eine vorhandene Azure Active Directory-Anwendung mit der Client-ID „xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx“ verwendet.
[2023-05-23T16:25:01.483Z] [Info] - Die botAadApp/create-Aktion wurde erfolgreich ausgeführt.
[2023-05-23T16:25:01.491Z] [Info] - Action botAadApp/create in lifecycle provision succeeded with output {"BOT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","SECRET_BOT_PASSWORD":"******"}
[2023-05-23T16:25:01.491Z] [Info] - Executing action botFramework/create in lifecycle provision
[2023-05-23T16:25:36.325Z] [Error] - Unable to execute action botFramework/create. Error message: API call to Developer Portal failed. Check [Output panel](command:fx-extension.showOutputChannel) for details.
[2023-05-23T16:25:36.330Z] [Info] - Failed to Execute lifecycle provision due to failed action: botFramework/create. DeveloperPortalAPIFailed:API call to Developer Portal failed: Error, Request failed with status code 400, API name: update-bot, X-Correlation-ID: 2e6ad175-f2ed-44bd-b274-d854ee150450. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "'MsaAppTenantId' property cannot be changed.. ". Env output: {"TEAMS_APP_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","TEAMS_APP_TENANT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","BOT_ID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","SECRET_BOT_PASSWORD":"******"}
[2023-05-23T16:25:36.335Z] [Info] - Execution summary:

Summary:
Fehler beim (×) Error: der Lebenszyklusstufe provision.
  (√) Done: aadApp/create wurde erfolgreich ausgeführt.
  (√) Done: teamsApp/create wurde erfolgreich ausgeführt.
    (√) Done: Die Teams-App mit der ID „ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx“ ist bereits vorhanden. Das Erstellen einer neuen Teams-App wurde übersprungen.
  (√) Done: botAadApp/create wurde erfolgreich ausgeführt.
    (√) Done: Es wurde eine vorhandene Azure Active Directory-Anwendung mit der Client-ID „ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx“ verwendet.
Fehler bei   (×) Error: botFramework/create.
    (×) Error: API call to Developer Portal failed: Error, Request failed with status code 400, API name: update-bot, X-Correlation-ID: 2e6ad175-f2ed-44bd-b274-d854ee150450. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "'MsaAppTenantId' property cannot be changed.. "
  (!) Warning: script wurde nicht ausgeführt.
  (!) Warning: aadApp/update wurde nicht ausgeführt.
  (!) Warning: teamsApp/validateManifest wurde nicht ausgeführt.
  (!) Warning: teamsApp/zipAppPackage wurde nicht ausgeführt.
  (!) Warning: teamsApp/validateAppPackage wurde nicht ausgeführt.
  (!) Warning: teamsApp/update wurde nicht ausgeführt.

[2023-05-23T16:25:36.443Z] [Error] - code:AppStudioPlugin.DeveloperPortalAPIFailed, message: API call to Developer Portal failed: Error, Request failed with status code 400, API name: update-bot, X-Correlation-ID: 2e6ad175-f2ed-44bd-b274-d854ee150450. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "'MsaAppTenantId' property cannot be changed.. "
stack: DeveloperPortalAPIFailed: API call to Developer Portal failed: Error, Request failed with status code 400, API name: update-bot, X-Correlation-ID: 2e6ad175-f2ed-44bd-b274-d854ee150450. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "'MsaAppTenantId' property cannot be changed.. "
    at Function.SystemError (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7515206)
    at Object.wrapException (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7479695)
    at handleBotFrameworkError (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7610407)
    at Function.updateBotRegistration (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7613744)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at LocalBotRegistration.createOrUpdateBotRegistration (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7622392)
    at CreateOrUpdateBotFrameworkBotDriver.handler (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6788222)
    at /Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6787267
    at Object.wrapRun (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7776133)
    at CreateOrUpdateBotFrameworkBotDriver.execute (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6787220)
    at CreateOrUpdateBotFrameworkBotDriver.<anonymous> (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6869134)
    at CreateOrUpdateBotFrameworkBotDriver.<anonymous> (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6868257)
    at Lifecycle.executeImpl (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6479922)
    at Lifecycle.execute (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6477323)
    at Coordinator.provision (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:6555464)
    at Coordinator.<anonymous> (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7115861)
    at FxCoreV3Implement.provisionResources (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7858229)
    at FxCoreV3Implement.exports.EnvWriterMW (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7119310)
    at FxCoreV3Implement.exports.ContextInjectorMW (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7970246)
    at FxCoreV3Implement.exports.ConcurrentLockerMW (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7952781)
    at Object.exports.envLoaderMWImpl (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7119257)
    at FxCoreV3Implement.<anonymous> (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7117796)
    at FxCoreV3Implement.<anonymous> (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7121915)
    at FxCoreV3Implement.exports.ProjectMigratorMWV3 (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:8061582)
    at FxCoreV3Implement.exports.ErrorHandlerMW (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7983320)
    at FxCoreV3Implement.dispatch (/Users/moritz/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.0.0/out/src/extension.js:2:7856596)
</pre>
</details>

**Comment by yukun-dong** [comment]
Hi @Radiergummi , thanks for reporting this issue.
The TTK currently supports Multi-tenant bot and doesn't support single-tenenat bot. Here are workaround steps for you:
1. Remove "botFramework/create" action in `teamsapp.local.yml`.
2. Start preview debugging.
3. After debugging starts, manually update your bot's endpoint to be "{{BOT_ENDPOINT}}/api/messages" on dev.botframework.com, you can find the real value of BOT_ENDPOINT in `env/.env.local` .

Please follow these steps and let me know if you encounter any issues.

**Comment by Radiergummi** [comment]
I chose to use a MultiTenant app in development instead, so I could keep using the automatic provisioning (want to keep this easy for junior devs), but hit some more trouble -- even with entirely fresh apps, messages sent from Teams would not arrive at my app unless the bot was migrated to Azure. Oh well. Been a bumpy road so far.

Is there an ETA on SingleTenant support, or is that not being considered currently? Thanks in advance.

**Comment by swatDong** [comment]
The missing message issue should be due to https://github.com/OfficeDev/TeamsFx/issues/8778 and now is resolved.
