### ISSUE TITLE
bug report: AppStudioPlugin.TeamsAppUpdateFailed

### ISSUE THREAD

**Issue by stevekftw** [OfficeDev/TeamsFx#8929]
Unable to update Teams app with ID 67b45474-22b9-4491-81a2-52bbd7af853b.

stack:
TeamsAppUpdateFailed: Unable to update Teams app with ID 67b45474-22b9-4491-81a2-52bbd7af853b.
	at AppStudioResultFactory.SystemError (<REDACTED: user-file-path>:2:7515206)
	at ConfigureTeamsAppDriver.update (<REDACTED: user-file-path>:2:6882717)
	at process.processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)
	at async ConfigureTeamsAppDriver.<anonymous> (<REDACTED: user-file-path>:2:6869134)
	at async ConfigureTeamsAppDriver.<anonymous> (<REDACTED: user-file-path>:2:6868257)
	at async ConfigureTeamsAppDriver.execute (<REDACTED: user-file-path>:2:6880162)
	at async Lifecycle.executeImpl (<REDACTED: user-file-path>:2:6479922)
	at async Lifecycle.execute (<REDACTED: user-file-path>:2:6477323)
	at async Coordinator.provision (<REDACTED: user-file-path>:2:6555464)
	at async Coordinator.<anonymous> (<REDACTED: user-file-path>:2:7115861)
	at async FxCoreV3Implement.provisionResources (<REDACTED: user-file-path>:2:7858229)
	at async exports.EnvWriterMW (<REDACTED: user-file-path>:2:7119310)
	at async exports.ContextInjectorMW (<REDACTED: user-file-path>:2:7970246)
	at async exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:7952781)
	at async exports.envLoaderMWImpl (<REDACTED: user-file-path>:2:7119257)
	at async FxCoreV3Implement.<anonymous> (<REDACTED: user-file-path>:2:7117796)
	at async FxCoreV3Implement.<anonymous> (<REDACTED: user-file-path>:2:7121915)
	at async exports.ProjectMigratorMWV3 (<REDACTED: user-file-path>:2:8061582)
	at async exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:7983320)
	at async FxCoreV3Implement.dispatch (<REDACTED: user-file-path>:2:7856596)

Console output

[2023-06-05T15:18:11.819Z] [Error] - code:AppStudioPlugin.TeamsAppUpdateFailed, message: Unable to update Teams app with ID 67b45474-22b9-4491-81a2-52bbd7af853b.
stack: TeamsAppUpdateFailed: Unable to update Teams app with ID 67b45474-22b9-4491-81a2-52bbd7af853b.
	at AppStudioResultFactory.SystemError (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7515206)
	at ConfigureTeamsAppDriver.update (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6882717)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ConfigureTeamsAppDriver.<anonymous> (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6869134)
	at async ConfigureTeamsAppDriver.<anonymous> (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6868257)
	at async ConfigureTeamsAppDriver.execute (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6880162)
	at async Lifecycle.executeImpl (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6479922)
	at async Lifecycle.execute (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6477323)
	at async Coordinator.provision (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:6555464)
	at async Coordinator.<anonymous> (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7115861)
	at async FxCoreV3Implement.provisionResources (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7858229)
	at async exports.EnvWriterMW (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7119310)
	at async exports.ContextInjectorMW (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7970246)
	at async exports.ConcurrentLockerMW (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7952781)
	at async exports.envLoaderMWImpl (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7119257)
	at async FxCoreV3Implement.<anonymous> (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7117796)
	at async FxCoreV3Implement.<anonymous> (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7121915)
	at async exports.ProjectMigratorMWV3 (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:8061582)
	at async exports.ErrorHandlerMW (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7983320)
	at async FxCoreV3Implement.dispatch (c:\Users\sk\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.0\out\src\extension.js:2:7856596)

**Comment by nliu-ms** [comment]
Hey @stevekftw , sorry for the inconvenience! The detailed error message has not been logged. Are you still meeting the error? If so, can you please try to open [Teams Developer Portal](https://dev.teams.microsoft.com/), sign in with your M365 account used in Teams Toolkit, and import the zip file under `appPackage\build\appPackage.xx.zip` to see if you can get detailed error message? Thanks!
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/e389d9d2-6882-4165-9f5c-7601a30f262e)
